Market offer specification langauge
golemfactory/golem-architecture pull request #108
Opened 2024-10-02 16:29 UTC by nieznanysprawiciel

2024-10-03 08:26 UTC, dopiera reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/108)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @nieznanysprawiciel)

___
*[`arch-snapshot/arch.md` line 447 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O8GKQLFBN8RwDcBp8xn:-O8GKQLFBN8RwDcBp8xo:btorady) ([raw file](https://github.com/golemfactory/golem-architecture/blob/bc736caeed8ac7050095eae67833ef3104d4e766/arch-snapshot/arch.md#L447)):*
> ```Markdown
> for trade, and to enable Requestors to discover those Providers and their service offers. A key element of this ecosystem
> is a generic specification language, which allows the expression of [Demand](#demand) and [Offer](#offer)
> artifacts—fundamental entities in Golem.
> ```

It seems to me it is the same language for both. In that case, can you mention it explicitly, please?



_Code quote:_
```Markdown
is a generic specification language, which allows the expression of [Demand](#demand) and [Offer](#offer)
artifacts—fundamental entities in Golem.
```
___
*[`arch-snapshot/arch.md` line 457 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O8GKc970YGZwQM92v89:-O8GKc970YGZwQM92v8A:b-l03w5h) ([raw file](https://github.com/golemfactory/golem-architecture/blob/bc736caeed8ac7050095eae67833ef3104d4e766/arch-snapshot/arch.md#L457)):*
> ```Markdown
>     easily add to it systematically.
> - **Constrained**: The language must prevent abuse (e.g., it must not allow the specification of resource conditions that
>     could result in endless resolution).
> ```

I am not sure what this means - can you please list an example of what endless resolution is?



_Code quote:_
```Markdown
- **Constrained**: The language must prevent abuse (e.g., it must not allow the specification of resource conditions that
    could result in endless resolution).
```
___
*[`arch-snapshot/arch.md` line 461 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O8GLkSNAP0mhpCEVSas:-O8GLkSNAP0mhpCEVSat:b-8jgv1e) ([raw file](https://github.com/golemfactory/golem-architecture/blob/bc736caeed8ac7050095eae67833ef3104d4e766/arch-snapshot/arch.md#L461)):*
Is there any way to define a schema? I.e. a way for  provider to say "I understand the VM schema defined in https://golem.network/schemas/vm.0.99.schema"? Something like XSD? Is there any repository of such schemas?

If the answer is no to both these questions we should write it.

BTW, I have a counter-proposal to the "typed key-pair" description. WDYT?
> The language is conceptually structured data like json, yaml or XML. Every layer (link to layers) of Golem puts constraints on this data. E.g. the Core Network requires that the field `golem` is a struct, that it has a field `runtime`, which is also a `struct`, which has a field `name` which is a struct and denotes the type of the ExeUnit (link).
> A VM ExeUnit type imposes further constraints, i.e. `golem` struct has to have an `inf` field, which is also a `struct`, which may have a field `cpu` (also type `struct`), which may have a field `capabilities`, which is a list of strings indicating CPU features.
> Provider- and Requestor Agents can impose further restrictions, e.g. there has to be a `golem.inf` `struct` has to have `geolocation` field (I'm making this up)...
> On top of the basic types introduced by json/XML/yaml, the property language introduces additional types:
> * ...
___
*[`arch-snapshot/arch.md` line 478 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O8GTjey3z9Ucfgd-ZOo:-O8GTjey3z9Ucfgd-ZOp:b5amnmx) ([raw file](https://github.com/golemfactory/golem-architecture/blob/bc736caeed8ac7050095eae67833ef3104d4e766/arch-snapshot/arch.md#L478)):*
> ```Markdown
> ###### Property types
> The properties are declared to be of a specific type, which is important as it has impact on how comparison operators work with properties of different types. The type of property is inferred from the literal used to specify the value.
> Following property types are supported:
> ```

What type does `golem.runtime` have?



_Code quote:_
```Markdown
Following property types are supported:
```
___
*[`arch-snapshot/arch.md` line 487 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O8GTD080NdpT-7ZjTYt:-O8GTD096_NSbCH6lCjx:braexve) ([raw file](https://github.com/golemfactory/golem-architecture/blob/bc736caeed8ac7050095eae67833ef3104d4e766/arch-snapshot/arch.md#L487)):*
Isn't this simpler:
> All elements on the list have to be of the same type.



_Code quote:_
```Markdown
The first item in the list declaration indicates the type of all elements in the list. If a List declaration contains literals indicating different types - a syntax error must be signalled by the parser.
```
___
*[`arch-snapshot/arch.md` line 491 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O8GTTLj2W4SkcJ-vKHa:-O8GTTLj2W4SkcJ-vKHb:bmxs7jl) ([raw file](https://github.com/golemfactory/golem-architecture/blob/bc736caeed8ac7050095eae67833ef3104d4e766/arch-snapshot/arch.md#L491)):*
> ```Markdown
>   The only operator applicable to List is ‘=’ (which is equivalent to “contains”), in 2 variants:
>   ‘=’ with a scalar value is resolved as “contains” (does a list contain one particular element),
>   ‘=’ with a list verifies if the property contains a list identical to the one specified in constraint expression.
> ```

This needs further explanation - I don't understand where operators come into play and how they are expressed.



_Code quote:_
```Markdown
  The only operator applicable to List is ‘=’ (which is equivalent to “contains”), in 2 variants:
  ‘=’ with a scalar value is resolved as “contains” (does a list contain one particular element),
  ‘=’ with a list verifies if the property contains a list identical to the one specified in constraint expression.
```
___
*[`arch-snapshot/arch.md` line 518 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O8GTwZ8BJzzJsarMlQi:-O8GTwZ92PIa30cnv8on:bds5vre) ([raw file](https://github.com/golemfactory/golem-architecture/blob/bc736caeed8ac7050095eae67833ef3104d4e766/arch-snapshot/arch.md#L518)):*
> ```Markdown
> The [example](#property-example) showed properties in a flattened form, where each key is a single string with dot
> separators. The Golem marketplace also supports other formats. One option is to use nested properties, which results in
> a JSON format:
> ```

Can we explicitly use the word "representation"? It is my understanding so far that properties are the same, but there are two ways of representing them textually, right?



_Code quote:_
```Markdown
The [example](#property-example) showed properties in a flattened form, where each key is a single string with dot
separators. The Golem marketplace also supports other formats. One option is to use nested properties, which results in
a JSON format:
```


<!-- Sent from Reviewable.io -->

2024-10-11 13:32 UTC, nieznanysprawiciel reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/108)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 478 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O8GTjey3z9Ucfgd-ZOo:-O8vk-W386JO4No-Zndr:b-r6bau0) ([raw file](https://github.com/golemfactory/golem-architecture/blob/bc736caeed8ac7050095eae67833ef3104d4e766/arch-snapshot/arch.md#L478)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

What type does `golem.runtime` have?
</blockquote></details>

`golem.runtime` doesn't have a type, because it is not a full property. It's only a namespace.
The question is if namespace without properties can be put in Offer/Demand. Technically it is possible, because we use json parsers that allow for it. But I must think if it has any meaning for the language. Probably we could use existence operator on it...

So I must think how to describe it and if it should be separate type or not
___
*[`arch-snapshot/arch.md` line 491 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O8GTTLj2W4SkcJ-vKHa:-O8vjFSsE239rYLjDYD9:b8r0syz) ([raw file](https://github.com/golemfactory/golem-architecture/blob/bc736caeed8ac7050095eae67833ef3104d4e766/arch-snapshot/arch.md#L491)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

This needs further explanation - I don't understand where operators come into play and how they are expressed.
</blockquote></details>

Moved to separate chapter about operators
___
*[`arch-snapshot/arch.md` line 518 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O8GTwZ8BJzzJsarMlQi:-O8HNcx97tU11lMkQRU1:b-896fix) ([raw file](https://github.com/golemfactory/golem-architecture/blob/bc736caeed8ac7050095eae67833ef3104d4e766/arch-snapshot/arch.md#L518)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Can we explicitly use the word "representation"? It is my understanding so far that properties are the same, but there are two ways of representing them textually, right?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-11 14:01 UTC, nieznanysprawiciel reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/108)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 447 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O8GKQLFBN8RwDcBp8xn:-O8vrTeU9fKoGWjXsy7w:ble3440) ([raw file](https://github.com/golemfactory/golem-architecture/blob/bc736caeed8ac7050095eae67833ef3104d4e766/arch-snapshot/arch.md#L447)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

It seems to me it is the same language for both. In that case, can you mention it explicitly, please?
</blockquote></details>

But I think it already follows from this paragraph. Can you propose how to make this more explicit?
___
*[`arch-snapshot/arch.md` line 457 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O8GKc970YGZwQM92v89:-O8vo7Kt8iaHN-tGqMft:b-v1hopo) ([raw file](https://github.com/golemfactory/golem-architecture/blob/bc736caeed8ac7050095eae67833ef3104d4e766/arch-snapshot/arch.md#L457)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I am not sure what this means - can you please list an example of what endless resolution is?
</blockquote></details>

For example if language would allow for writing functions, you could create recursive function that never ends. These are initial assumptions that I copy-pasted from design documents. I can't show example in the language, because it was designed to not allow for endless resolution :D 
It's rather hard to describe examples here, before telling readers what is this language for


<!-- Sent from Reviewable.io -->

2024-10-14 17:01 UTC, nieznanysprawiciel reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/108)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 461 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O8GLkSNAP0mhpCEVSas:-O8vtYfv8vGFP0mEiTSt:bazpbiz) ([raw file](https://github.com/golemfactory/golem-architecture/blob/bc736caeed8ac7050095eae67833ef3104d4e766/arch-snapshot/arch.md#L461)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Is there any way to define a schema? I.e. a way for  provider to say "I understand the VM schema defined in https://golem.network/schemas/vm.0.99.schema"? Something like XSD? Is there any repository of such schemas?

If the answer is no to both these questions we should write it.

BTW, I have a counter-proposal to the "typed key-pair" description. WDYT?
> The language is conceptually structured data like json, yaml or XML. Every layer (link to layers) of Golem puts constraints on this data. E.g. the Core Network requires that the field `golem` is a struct, that it has a field `runtime`, which is also a `struct`, which has a field `name` which is a struct and denotes the type of the ExeUnit (link).
> A VM ExeUnit type imposes further constraints, i.e. `golem` struct has to have an `inf` field, which is also a `struct`, which may have a field `cpu` (also type `struct`), which may have a field `capabilities`, which is a list of strings indicating CPU features.
> Provider- and Requestor Agents can impose further restrictions, e.g. there has to be a `golem.inf` `struct` has to have `geolocation` field (I'm making this up)...
> On top of the basic types introduced by json/XML/yaml, the property language introduces additional types:
> * ...
</blockquote></details>

I finished the chapter about specification language. The questions you are asking are answered, but not in one place. They are spread thematically across a few chapters. Please take a look if it explains everything.

About your proposal: in general it is not true. I mean not only examples, but the idea of mapping layers on the data in the Offer.
On the other side there is a grain of truth here, because some components have functions for adding certain properties, but I would say that it is rather matter of implementation. This chapter rather describes ideas.
We can discuss this further, but please read whole chapter as a starting point for this discussion.


<!-- Sent from Reviewable.io -->

2024-10-17 18:27 UTC, dopiera requested changes
In general this looks pretty good. I've left some comments, though.

Could you please separate the unrelated changes to another PR, please? Especially that they should end up on the master branch.

> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-:-O9QiNvuDG8uBZ8HEcbQ:bdj0koh)* status: 0 of 6 files reviewed, 26 unresolved discussions (waiting on @nieznanysprawiciel)

___
*[`arch-snapshot/arch.md` line 457 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O8GKc970YGZwQM92v89:-O9JZh1b6RReJFjkiKeQ:bmnaiqz) ([raw file](https://github.com/golemfactory/golem-architecture/blob/bc736caeed8ac7050095eae67833ef3104d4e766/arch-snapshot/arch.md#L457)):*
How about describe it directly, then?
> The language must ensure that no formulas can be written that result in infinite or excessively long evaluation times.

BTW, why do we need this? If I am correct, the Provider Agent's Yagna. As a user, the Yagna which I'm controlling is only running the constraints defined by me, not by some other agents, no?
___
*[`arch-snapshot/arch.md` line 478 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O8GTjey3z9Ucfgd-ZOo:-O9KDq2g0R0_V2jYmXH-:bo59uxj) ([raw file](https://github.com/golemfactory/golem-architecture/blob/bc736caeed8ac7050095eae67833ef3104d4e766/arch-snapshot/arch.md#L478)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

`golem.runtime` doesn't have a type, because it is not a full property. It's only a namespace.
The question is if namespace without properties can be put in Offer/Demand. Technically it is possible, because we use json parsers that allow for it. But I must think if it has any meaning for the language. Probably we could use existence operator on it...

So I must think how to describe it and if it should be separate type or not
</blockquote></details>

Did I just uncover that the language is defined by its implementation? ;)

Either way, we should describe what a namespace is. BTW, wouldn't it be conceptually easier to just create a "struct" property type and say that `golem.runtime` is a struct? You wouldn't need the "namespace" entity.
___
*[`arch-snapshot/arch.md` line 2 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9KPD8m9SFcN89ZYjQ5:-O9KPD8m9SFcN89ZYjQ6:b6kgu1y) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L2)):*
> ```Markdown
> # Golem — current architecture
> ```

Can you please revert unrelated changes?
___
*[`arch-snapshot/arch.md` line 521 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9JibVYELKIOGcu9v-F:-O9JibVYELKIOGcu9v-G:bns4jfj) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L521)):*
> ```Markdown
> for trade, and to enable Requestors to discover those Providers and their service offers. A key element of this ecosystem
> is a generic specification language, which allows the expression of [Demand](#demand) and [Offer](#offer)
> artifacts—fundamental entities in Golem.
> ```

I would appreciate more intuition on this section. As a reader, my initial thoughts are:

- You need a way to describe arbitrary resources in a structured format – this brings to mind formats like JSON, XML, YAML, etc.
  - You'd also need a mechanism to impose a partial schema, which suggests tools like XSD, JSON Schema, or similar.
- To filter resources, you would likely write constraints – something akin to `jq`, XPath, or similar query languages.

However, I suspect these assumptions might not align well with Golem's design, particularly since the same language is used both to describe resources and to filter them. Initially, this seems unconventional. Could you clarify the rationale behind this approach and explain why more obvious solutions (like using separate tools for each) are not applicable here?



_Code quote:_
```Markdown
The fundamental feature of the Golem network and ecosystem is to enable Providers to offer their computing resources
for trade, and to enable Requestors to discover those Providers and their service offers. A key element of this ecosystem
is a generic specification language, which allows the expression of [Demand](#demand) and [Offer](#offer)
artifacts—fundamental entities in Golem.
```
___
*[`arch-snapshot/arch.md` line 530 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9Jcxur4HseV_Qg4DFU:-O9Jcxur4HseV_Qg4DFV:bch5yao) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L530)):*
> ```Markdown
>   (e.g., trading conditions, terms of business, etc.).
> - **Scalable**: The language should be openly extensible in an intuitive way, allowing parties in the Golem ecosystem to
>   easily add to it systematically.
> ```

I thought that the language stays the same but it used to describe resources not known upfront, no?



_Code quote:_
```Markdown
- **Scalable**: The language should be openly extensible in an intuitive way, allowing parties in the Golem ecosystem to
  easily add to it systematically.
```
___
*[`arch-snapshot/arch.md` line 534 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9JdaI-0ujDxKB-sLzI:-O9JdaI-0ujDxKB-sLzJ:bcbtf2r) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L534)):*
I don't get it - how is it different from **Versatile**? Don't both of these points boil down to
> the language needs to make it possible to describe resources unknown to the language creators

Also, I'm not sure what you mean by the word "abstract" in this context.

Also - what do you mean by "patterns"? As in "design patterns"? Are the repositories something philosophically different from good documentation?



_Code quote:_
```Markdown
- **Open**: The language should be abstract, but its possible applications must be highlighted through examples and pattern
  repositories.
```
___
*[`arch-snapshot/arch.md` line 536 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9KCw6nAzDDNFRBGMMG:-O9KCw6nAzDDNFRBGMMH:b7waq33) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L536)):*
> ```Markdown
>   repositories.
> 
> ##### Properties
> ```

Before we dive into properties, can you say something more about the language?

Is the "language" just a list of properties and constraints? In any order?



_Code quote:_
```Markdown
##### Properties
```
___
*[`arch-snapshot/arch.md` line 548 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9KOrQEEXEsCmnQ308S:-O9KOrQEEXEsCmnQ308T:bwkbq28) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L548)):*
> ```Markdown
> 
> A property name may include any character apart from ‘special’ characters ([,],=,*,$). It is recommended that
> properties follow a hierarchical namespace convention, such as `golem.node.cpu.cores`, which helps categorize property
> ```

Is this just a convention, really?

Can I write
```
golem.foo: 5
golem.foo.bar: "baz"
```
?

If yes, how do I represent it in json?



_Code quote:_
```Markdown
convention
```
___
*[`arch-snapshot/arch.md` line 557 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9KRkqACN-5sZYnlZbk:-O9KRkqACN-5sZYnlZbl:b-g9gn5z) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L557)):*
> ```Markdown
> Following property types are supported:
> 
> - **String** - any value declared in quotes, eg: “sample text”
> ```

What about escaping? `"""` satisfies your definition, but I don't think this is really valid. BTW, are you speaking a [...]

2024-10-22 12:58 UTC, nieznanysprawiciel reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/108)* status: 0 of 6 files reviewed, 26 unresolved discussions (waiting on @dopiera and @tag)

___
*[`arch-snapshot/arch.md` line 457 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O8GKc970YGZwQM92v89:-O9oCFGy4lhQPOxADeGk:bjshzc2) ([raw file](https://github.com/golemfactory/golem-architecture/blob/bc736caeed8ac7050095eae67833ef3104d4e766/arch-snapshot/arch.md#L457)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

How about describe it directly, then?
> The language must ensure that no formulas can be written that result in infinite or excessively long evaluation times.

BTW, why do we need this? If I am correct, the Provider Agent's Yagna. As a user, the Yagna which I'm controlling is only running the constraints defined by me, not by some other agents, no?
</blockquote></details>

No. Both Demand and Offer have constraints. You run both
___
*[`arch-snapshot/arch.md` line 478 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O8GTjey3z9Ucfgd-ZOo:-O9oGaVZ3ZweI0nsjfa_:bbuyyld) ([raw file](https://github.com/golemfactory/golem-architecture/blob/bc736caeed8ac7050095eae67833ef3104d4e766/arch-snapshot/arch.md#L478)):*
> Did I just uncover that the language is defined by its implementation? ;)
Rather that the design wasn't fully followed during implementation

Yes, I think it is better to introduce structs. Especially that it will solve the problem with lists as well.
___
*[`arch-snapshot/arch.md` line 521 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9JibVYELKIOGcu9v-F:-O9oBA0--VF_IxUR6yu7:bqxfkxw) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L521)):*
> since the same language is used both to describe resources and to filter them
What do you mean? Properties are used to declare things and constraints to filter. So there are separate languages.
Unless you think of Demand as a filter, which it is not, because Demand declares stuff as well
___
*[`arch-snapshot/arch.md` line 548 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9KOrQEEXEsCmnQ308S:-O9oEPmt2vxs8Gc18sIq:bbkokat) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L548)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Is this just a convention, really?

Can I write
```
golem.foo: 5
golem.foo.bar: "baz"
```
?

If yes, how do I represent it in json?
</blockquote></details>

Yes, you can.
Json makes something like this:
{
  "golem": {
	"foo": {
	  "@tag": 5,
	  "bar": "baz"
	}
  }
}
I will include this in example.

(By the way: flat from requires quotes around keys. It effectively is a json as well)
___
*[`arch-snapshot/arch.md` line 566 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9KPlyV7FyALKtLK_Iz:-O9oH4TN5cdK7cx0ZQ1C:b-8k6j9r) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L566)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

So you cannot have a list of lists?

Or consider this scenario - let's say in the future (I know it's not doable today) I'll be interested in picking a storage device which need to match my criteria. A natural way of achieving this would be to make providers describe the available storage devices as a list:
```
[
  {
    "capacity": 2048G,
    "type": "ssd",
    "sector_size": 4k,
    "erase_block": 256K
   },
   {
    "capacity": 4096G,
    "type": "smr",
    "sector_size": 4k
   }
]
```

Am I correct that the language doesn't support it?
</blockquote></details>

You can do this. But I'm not sure if you will be able to write meaningful constraint.
As I assume you draw this conclusion from the fact, that the struct is not one of listed type. I'm planning to add structs to the list.
___
*[`arch-snapshot/arch.md` line 642 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9KNO_S-l2wAB3X6onB:-O9oIWeJ0EV6HQcV5zud:bbbu4bb) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L642)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I don't get it - why introduce another entity (value-less property) rather than introduce another type of property - `null`.
</blockquote></details>

Because meaning of value-less property is different. It is not a type. It doesn't say that value is null. It says that value exists and can be revealed on request.
___
*[`arch-snapshot/arch.md` line 661 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9KfDHW9Bpuyh9VfZVw:-O9o7PU19LPK8QCwH1ga:b-896fix) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L661)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

we agreed on the passive form
</blockquote></details>

Done.
___
*[`arch-snapshot/arch.md` line 665 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9KHxMpBEWpkhJAWzSq:-O9o61WQ2C8dRx85L868:b82hkob) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L665)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

This choice surprises me. Can you elaborate on why it was chosen over alternatives? In particular, I'm wondering why not pick a language designed to query structured data?

E.g. am I correct that I cannot express in the language that I want 2GB of RAM for every core?
</blockquote></details>

Actually I don't know the justification for this decision, I wasn't part of designing team. You should ask Rekuc.

About the query: It's not possible I think.
There is concept of pseudo-functions in original design, but it is dead concept: https://docs.google.com/document/d/1tzMrhdBr9wiUXtSn1JO18MmIiP31dkMakdjStnF3eZY/edit?tab=t.0#heading=h.qdxvpfm68oay
___
*[`arch-snapshot/arch.md` line 672 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9KsW7p8xYl8_oa3Ge9:-O9o1XRZ4VxEMn1CQ6Tr:bremls7) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L672)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

What do you mean by aspect? What, other than the value can be referenced?
</blockquote></details>

Ups, sorry, leftover.
Aspects were in original design, I removed them since they were dead feature and no one was even planning to use them at this moment.
https://docs.google.com/document/d/1tzMrhdBr9wiUXtSn1JO18MmIiP31dkMakdjStnF3eZY/edit?tab=t.0#heading=h.xljbllnqnd9i
___
*[`arch-snapshot/arch.md` line 678 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9Ktq5X8VIAqQMaE3eO:-O9o-dF16gya1ytl77e7:ba3iel4) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L678)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

What does `golem.inf.ram>=` mean? (It seems to pass your regex).
</blockquote></details>

It's good point, that regex is not fully correct.
It is due to the fact that existence operator `=*` doesn't have value, but as a side effect your example passes as well.
___
*[`arch-snapshot/arch.md` line 709 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9Q1Ma9-78fyR54egwW:-O9o-94W27DBPUcTXGwZ:bdtbiha) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887 [...]

2024-10-22 14:35 UTC, nieznanysprawiciel reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/108)* status: 0 of 6 files reviewed, 26 unresolved discussions (waiting on @dopiera and @tag)

___
*[`arch-snapshot/arch.md` line 457 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O8GKc970YGZwQM92v89:-O9oPMQD0gDDrZO2j8K4:b10xsha) ([raw file](https://github.com/golemfactory/golem-architecture/blob/bc736caeed8ac7050095eae67833ef3104d4e766/arch-snapshot/arch.md#L457)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

No. Both Demand and Offer have constraints. You run both
</blockquote></details>

And about listing examples: the point is about avoiding abuse of the language. Endless resolution is already mentioned as example. So forcing me to write an example will end in endless resolution.
And more seriously: I don't know what is unclear in endless resolution, can you propose different phrasing?
___
*[`arch-snapshot/arch.md` line 521 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9JibVYELKIOGcu9v-F:-O9oMz4s9X-os_YHvXZH:bbr269c) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L521)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

> since the same language is used both to describe resources and to filter them
What do you mean? Properties are used to declare things and constraints to filter. So there are separate languages.
Unless you think of Demand as a filter, which it is not, because Demand declares stuff as well
</blockquote></details>

Sorry, everything was formatted as quote in previous comment

What do you mean? Properties are used to declare things and constraints to filter. So there are separate languages.  
Unless you think of Demand as a filter, which it is not, because Demand declares stuff as well
___
*[`arch-snapshot/arch.md` line 530 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9Jcxur4HseV_Qg4DFU:-O9odk6m1c5Mmk_omF6-:b9gu2er) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L530)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I thought that the language stays the same but it used to describe resources not known upfront, no?
</blockquote></details>

Rephrased
___
*[`arch-snapshot/arch.md` line 534 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9JdaI-0ujDxKB-sLzI:-O9oNlswDrVybVCm_H0f:b-hmx8ou) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L534)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I don't get it - how is it different from **Versatile**? Don't both of these points boil down to
> the language needs to make it possible to describe resources unknown to the language creators

Also, I'm not sure what you mean by the word "abstract" in this context.

Also - what do you mean by "patterns"? As in "design patterns"? Are the repositories something philosophically different from good documentation?
</blockquote></details>

Removed.
I thought I will make my life easier by copying from existing documents, but it seems not :D
___
*[`arch-snapshot/arch.md` line 790 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9L4DAJACLgIJN_N9CP:-O9oKgI-E1EzEjvuP1xv:bl59mp6) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L790)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Can you please give examples of such rules?
</blockquote></details>

I give 3 chapters of example 2 paragraphs later :(


<!-- Sent from Reviewable.io -->

2024-10-22 14:40 UTC, nieznanysprawiciel reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/108)* status: 0 of 6 files reviewed, 26 unresolved discussions (waiting on @dopiera and @tag)

___
*[`arch-snapshot/arch.md` line 944 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9QZi2N7LBGc0AzkT7T:-O9oeeey8_nNom00g2k-:bbxudhw) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L944)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

While this section is very informative, I think it lacks a conclusion. 

~What are the measures which need to be employed? Should one care about backwards compatibility or, provided that there are no silent failures, can one introduce breaking changes? Or should there be major versions?~

EDIT:
Oh - I see now. Can you please add a sentence along the lines of:
> Different policies are required for different aspects of the protocol. The following subsections describe the key ones.

EDIT:
but there is only one aspect - the negotiation protocol. Maybe you should just inline the next subsection?
</blockquote></details>

I'm not sure if I understand correctly: you would like to remove header `Negotiation protocols compatibility` and inline text?
I would prefer to keep subsections for easier reading.


<!-- Sent from Reviewable.io -->

2024-10-22 15:28 UTC, nieznanysprawiciel reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/108)* status: 0 of 6 files reviewed, 26 unresolved discussions (waiting on @dopiera and @tag)

___
*[`arch-snapshot/arch.md` line 536 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9KCw6nAzDDNFRBGMMG:-O9opfMm1tgmjDfTzFWU:bpp1jle) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L536)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Before we dive into properties, can you say something more about the language?

Is the "language" just a list of properties and constraints? In any order?
</blockquote></details>

Take a look
___
*[`arch-snapshot/arch.md` line 557 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9KRkqACN-5sZYnlZbk:-O9oj8NvA75f9meCeJXY:b-rn6at3) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L557)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

What about escaping? `"""` satisfies your definition, but I don't think this is really valid. BTW, are you speaking about the JSON or flat representation? Maybe you should split the two aspects of this list into:
* types - i.e. what can be stored, how exact will it be (e.g. in case of the decimal type - what is its precision and limits)
* literals - i.e. how are they denoted in the textual format, e.g. for strings it is far from obvious (escaping, multilines, encodings, etc.) so feel free to mention it is implementation-defined or "according to RFC XYZ"
</blockquote></details>

I added reference to specification where I could. I don't think we have any specification for decimals for example.

By the way: in the past specification language allowed yaml representation, but I think it's time to consciously abandon it here since it was unused anyway.
___
*[`arch-snapshot/arch.md` line 792 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9Q2AjGBJWhAbQFtSBv:-O9ohhn_1724hjd9hMWq:byakhuo) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L792)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

How are those protocols specified? Is this just a piece of documentation which both the requstor- and provider agents should follow? Or is it somehow programatically described in some DSL?
</blockquote></details>

I linked to chapter about managing protocols specification
___
*[`arch-snapshot/arch.md` line 864 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9QRcBBA5gCsedSPcrA:-O9oi9lk3au21GXxxS93:bthm7kw) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L864)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Maybe "reference implementation" would be more future-proof?
</blockquote></details>

I think it will rather complicate description and we are describing snapshot anyway


<!-- Sent from Reviewable.io -->

2024-10-22 16:54 UTC, nieznanysprawiciel reviewed
Done

> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-:-O9p8bWn5wBEQMymzybT:bb6un1j)* status: 0 of 6 files reviewed, 26 unresolved discussions (waiting on @dopiera and @tag)

___
*[`arch-snapshot/arch.md` line 2 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9KPD8m9SFcN89ZYjQ5:-O9p8Uz_8M-goxr_WYgQ:b-896fix) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L2)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Can you please revert unrelated changes?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-23 23:05 UTC, dopiera requested changes
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/108)* status: 0 of 6 files reviewed, 8 unresolved discussions (waiting on @nieznanysprawiciel)

___
*[`arch-snapshot/arch.md` line 457 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O8GKc970YGZwQM92v89:-O9vZit_BQzb6nn1VXG4:b-43rbno) ([raw file](https://github.com/golemfactory/golem-architecture/blob/bc736caeed8ac7050095eae67833ef3104d4e766/arch-snapshot/arch.md#L457)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

And about listing examples: the point is about avoiding abuse of the language. Endless resolution is already mentioned as example. So forcing me to write an example will end in endless resolution.
And more seriously: I don't know what is unclear in endless resolution, can you propose different phrasing?
</blockquote></details>

ACK regarding running both.

I think it's the word "resolution" which made it unclear to me.  I think "evaluation" suits this context better.
___
*[`arch-snapshot/arch.md` line 2 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9KPD8m9SFcN89ZYjQ5:-O9vc8S47cFwVsjy3uNC:bwutxz0) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L2)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Some are still there (in other files)
___
*[`arch-snapshot/arch.md` line 521 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9JibVYELKIOGcu9v-F:-O9vYGki2pf9Na9GAdyM:b-66rbiv) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L521)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

Sorry, everything was formatted as quote in previous comment

What do you mean? Properties are used to declare things and constraints to filter. So there are separate languages.  
Unless you think of Demand as a filter, which it is not, because Demand declares stuff as well
</blockquote></details>

My question boils down to "why design a language (or even two) rather than take existing ones"? And also 
___
*[`arch-snapshot/arch.md` line 534 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9JdaI-0ujDxKB-sLzI:-O9v_IRL3nzNFd1YTJNa:bsqkrb) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L534)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

Removed.
I thought I will make my life easier by copying from existing documents, but it seems not :D
</blockquote></details>

![download.jpeg](https://files.reviewableusercontent.io/images/reviewable/406969/Ikvtxn6F8b2BJ_5Fwi1FQGKF/download.jpeg)
file:///tmp/download.jpeg
___
*[`arch-snapshot/arch.md` line 536 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9KCw6nAzDDNFRBGMMG:-O9v_iui0_AuraV0qqZ2:bb0ojpg) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L536)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

Take a look
</blockquote></details>

No bonus points for writing it twice. ;) I prefer the one after GPT-ing ;)
___
*[`arch-snapshot/arch.md` line 678 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9Ktq5X8VIAqQMaE3eO:-O9vb1BjC0iqq9ye_rKF:b16w9vk) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L678)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

It's good point, that regex is not fully correct.
It is due to the fact that existence operator `=*` doesn't have value, but as a side effect your example passes as well.
</blockquote></details>

Perhaps it's worth writing the regex for a mandatory value and then list the unary operator `=*` as yet another allowed form?
___
*[`arch-snapshot/arch.md` line 833 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9Q70cj1eaNdIhDJqSs:-O9vbbfrD_Rm2G3q4euV:b-la8ekp) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L833)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

It's just naming convention.
It is stated in linked document by the way. Do you want me to mention it explicite here?
</blockquote></details>

Without diving into detail - yes please
___
*[`arch-snapshot/arch.md` line 574 at r10](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9vaHiF6GXslyps_gbU:-O9vaHiF6GXslyps_gbV:bvwmac9) ([raw file](https://github.com/golemfactory/golem-architecture/blob/d9adfe9ba4f4729ce4cf2b67cf589e4a70da957c/arch-snapshot/arch.md#L574)):*
> ```Markdown
> work with properties of different types. The type of property is inferred from the literal used to specify the value.
> Following property types are supported:
> - **String** - any value declared in quotes, eg: “sample text”
> ```

Let's leave just one



_Code quote:_
```Markdown
- **String** - any value declared in quotes, eg: “sample text”
```
___
*[`arch-snapshot/arch.md` line 656 at r10](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9vacLTD5coqTWfvD9t:-O9vacLTD5coqTWfvD9u:bd3x149) ([raw file](https://github.com/golemfactory/golem-architecture/blob/d9adfe9ba4f4729ce4cf2b67cf589e4a70da957c/arch-snapshot/arch.md#L656)):*
> ```Markdown
>       "pricing": {
>         "model": {
>           "@tag": "linear",
> ```

this is great, but I think this has special meaning, which should be expained



_Code quote:_
```Markdown
@tag"
```


<!-- Sent from Reviewable.io -->

2024-10-24 14:41 UTC, nieznanysprawiciel reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/108)* status: 0 of 6 files reviewed, 8 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 2 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9KPD8m9SFcN89ZYjQ5:-O9yyFcwB3_a-6DIo-SP:b-ujp7p7) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L2)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Some are still there (in other files)
</blockquote></details>

Those are related changes, because I link to those in some paragraphs, so I wanted to make sure that the places that these links lead to have decent content


<!-- Sent from Reviewable.io -->

2024-10-24 16:09 UTC, nieznanysprawiciel reviewed
> Dismissed @dopiera from a discussion.
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/108)* status: 0 of 6 files reviewed, 7 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 536 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9KCw6nAzDDNFRBGMMG:-O9z1S_zBKX5_75RBGKE:b-896fix) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L536)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

No bonus points for writing it twice. ;) I prefer the one after GPT-ing ;)
</blockquote></details>

Done.
___
*[`arch-snapshot/arch.md` line 678 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9Ktq5X8VIAqQMaE3eO:-O9z52HR3z0qoYGOF6gF:b-896fix) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L678)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Perhaps it's worth writing the regex for a mandatory value and then list the unary operator `=*` as yet another allowed form?
</blockquote></details>

Done.
___
*[`arch-snapshot/arch.md` line 833 at r6](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9Q70cj1eaNdIhDJqSs:-O9zGwgwA1AnIb69NrX1:b-896fix) ([raw file](https://github.com/golemfactory/golem-architecture/blob/115d6641fd1e54d651ea887ff9b5f74aa34a2942/arch-snapshot/arch.md#L833)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Without diving into detail - yes please
</blockquote></details>

Done.
___
*[`arch-snapshot/arch.md` line 574 at r10](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9vaHiF6GXslyps_gbU:-O9z1amTDXB28qXfSJ5J:b-896fix) ([raw file](https://github.com/golemfactory/golem-architecture/blob/d9adfe9ba4f4729ce4cf2b67cf589e4a70da957c/arch-snapshot/arch.md#L574)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Let's leave just one
</blockquote></details>

Done.
___
*[`arch-snapshot/arch.md` line 656 at r10](https://reviewable.io/reviews/golemfactory/golem-architecture/108#-O9vacLTD5coqTWfvD9t:-O9z4UsZ2r_VMjKfpcKU:bywhcj8) ([raw file](https://github.com/golemfactory/golem-architecture/blob/d9adfe9ba4f4729ce4cf2b67cf589e4a70da957c/arch-snapshot/arch.md#L656)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

this is great, but I think this has special meaning, which should be expained
</blockquote></details>

Explanation added


<!-- Sent from Reviewable.io -->

2024-10-24 16:13 UTC, dopiera approved these changes
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/108)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @nieznanysprawiciel)



<!-- Sent from Reviewable.io -->

2024-10-24 16:27 UTC, merged