payment components rev1
golemfactory/golem-architecture pull request #110
Opened 2024-10-04 10:03 UTC by kamirr

2024-10-04 15:47 UTC, dopiera reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/110)* status: 0 of 1 files reviewed, 17 unresolved discussions (waiting on @kamirr)

___
*[`arch-snapshot/arch.md` line 534 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O8MLDIo09RNa1EMOD_j:-O8MLDIo09RNa1EMOD_k:bthdsam) ([raw file](https://github.com/golemfactory/golem-architecture/blob/5fd05a316d40032f5a8180668d962f2dbd7c0d50/arch-snapshot/arch.md#L534)):*
> ```Markdown
> * Algorithm overview
> 
> ### Payments
> ```

Since we're describing a payments component here, let's start with its interface. Let's not dive into code or the nitty-gritty, obscure details but the general idea. In particular I would like to learn:
* Which other components the does payments component interacts with?
* What is the relationship of this component to other components? (e.g. is there one per Agreement?)
* What is the lifecycle of this component?
* How do the other components invoke those payments (I presume there are multiple hooks in the process of performing Activities but honestly, I have no clue, so please describe them)? E.g.
  * when in the process?
  * what purpose do those serve?
  * what do they do?

If this component is further subdivided (e.g. some fixed part and swappable payment drivers), please include a decomposition of this component.



_Code quote:_
```Markdown
### Payments
```
___
*[`arch-snapshot/arch.md` line 536 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O8Mz2gqEz3MZPLcRM7Z:-O8Mz2gqEz3MZPLcRM7_:buj7eng) ([raw file](https://github.com/golemfactory/golem-architecture/blob/5fd05a316d40032f5a8180668d962f2dbd7c0d50/arch-snapshot/arch.md#L536)):*
> ```Markdown
> ### Payments
> #### Important terms
> 1. Payment platform – a 3-part identifier uniquely describing a mode of
> ```

Is a "Payment platform" really only an identifier? Or is it a piece of software identified only identified by that identifier?



_Code quote:_
```Markdown
 Payment platform – a 3-part identifier 
```
___
*[`arch-snapshot/arch.md` line 537 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O8MOEt634iXSdAtwkeQ:-O8MOEt634iXSdAtwkeR:b-254ly0) ([raw file](https://github.com/golemfactory/golem-architecture/blob/5fd05a316d40032f5a8180668d962f2dbd7c0d50/arch-snapshot/arch.md#L537)):*
> ```Markdown
> #### Important terms
> 1. Payment platform – a 3-part identifier uniquely describing a mode of
>     exchanging funds. It is composed of 3 fields:
> ```

Dumb question - why is that so? I'm guessing that the driver dictates the meaning of the `network` and `token` fields. If their meaning is implementation-defined, why do we bother to structure them into `token` and and `network` rather than have a generic, implementation defined `driver_config`? It seems to me that some assumptions about the driver have been made here. E.g. can we use PayU? If no - why? What are these assumptions?
___
*[`arch-snapshot/arch.md` line 539 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O8MO51xCPUwVsSuh-lI:-O8MO51xCPUwVsSuh-lJ:b-k10qr6) ([raw file](https://github.com/golemfactory/golem-architecture/blob/5fd05a316d40032f5a8180668d962f2dbd7c0d50/arch-snapshot/arch.md#L539)):*
> ```Markdown
>     exchanging funds. It is composed of 3 fields:
>     - driver – Determines which driver to select, see below for details.
>     -  network – Defined by the driver.
> ```

extra space?
___
*[`arch-snapshot/arch.md` line 543 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O8MWnx48dQxchWU2Mn2:-O8MWnx48dQxchWU2Mn3:b-nusf3a) ([raw file](https://github.com/golemfactory/golem-architecture/blob/5fd05a316d40032f5a8180668d962f2dbd7c0d50/arch-snapshot/arch.md#L543)):*
> ```Markdown
>       The payment platform is opaque to Golem and are only relevant for payments.
>       It is serialized as `{dirver}-{network}-{token}`
> #### Payments models
> ```

I don't understand why there is enumeration in this subsection. Especially the second point seems disconnected from the other two. Is this the right text structure optimal here? 



_Code quote:_
```Markdown
#### Payments models
```
___
*[`arch-snapshot/arch.md` line 545 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O8MRWAU0COTzR-5dudl:-O8MRWAU0COTzR-5dudm:b-5l6hjs) ([raw file](https://github.com/golemfactory/golem-architecture/blob/5fd05a316d40032f5a8180668d962f2dbd7c0d50/arch-snapshot/arch.md#L545)):*
It's unclear to me what you mean by "abstract computation". Would this be still true?
> - A payment model is an algorithm for determining the resource price based on resource usage (AKA Usage Counters)

BTW, is it the payment model, which governs whether there are mid-agreement payments? If yes, let's write explicitly about it because it is not clear neither from your or my description.

An example would be nice, so that the reader can build an intuition.



_Code quote:_
```Markdown
- A payment model is an abstract computation which describes how to map usage
  counters (see `ExeUnits` section) to an amount of currency due.
```
___
*[`arch-snapshot/arch.md` line 550 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O8MZdt6-qOhJGdRMpJ5:-O8MZdt6-qOhJGdRMpJ6:b-hjzh6m) ([raw file](https://github.com/golemfactory/golem-architecture/blob/5fd05a316d40032f5a8180668d962f2dbd7c0d50/arch-snapshot/arch.md#L550)):*
This point seems a bit out of place. Or was your intention to describe how an implementation of this layer is instantiated? If that is the case than please make it explicit. E.g.
> A Payment Model is an inherent part of an Agreement. It is subject to negotiation between ...



_Code quote:_
```Markdown
- Negotiation:
  - Offer shall expose a property `golem.com.pricing.model` which is a string
    containing the model name, e.g. `linear`, as well as
    `golem.com.pricing.model.{model_name}` which is an object containing
    model-specific parameters.
```
___
*[`arch-snapshot/arch.md` line 555 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O8MaOJj9_p-xuNBwOCi:-O8MaOJj9_p-xuNBwOCj:by1rjci) ([raw file](https://github.com/golemfactory/golem-architecture/blob/5fd05a316d40032f5a8180668d962f2dbd7c0d50/arch-snapshot/arch.md#L555)):*
> ```Markdown
>   counters by constant coefficients and adds a constant on top of that, thus
>   forming a linear function. The counters used today by yagna are cpu-time
>   and total run-time.
> ```

This needs to be expanded. Where do the constant coefficients and the constant come from? If I'm not mistaken, the usage counters are defined by the execution layer. If so, are payment models execution unit specific?

BTW, are there no counters for GPU time or memory (be it main memory or GPU memory)?



_Code quote:_
```Markdown
- The linear payment model is the only one currently in use. It multiplies usage
  counters by constant coefficients and adds a constant on top of that, thus
  forming a linear function. The counters used today by yagna are cpu-time
  and total run-time.
```
___
*[`arch-snapshot/arch.md` line 556 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O8Mi256EdsiKbl52_nq:-O8Mi256EdsiKbl52_nr:bht7ijl) ([raw file](https://github.com/golemfactory/golem-architecture/blob/5fd05a316d40032f5a8180668d962f2dbd7c0d50/arch-snapshot/arch.md#L556)):*
> ```Markdown
>   forming a linear function. The counters used today by yagna are cpu-time
>   and total run-time.
> #### Payments flow during Agreement
> ```

"during the lifetime of the Agreement", right?



_Code quote:_
```Markdown
during Agreement
```
___
*[`arch-snapshot/arch.md` line 556 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O8N9kpF1SIx8nLrL2A4:-O8N9kpF1SIx8nLrL2A5:b1fcx29) ([raw file](https://github.com/golemfactory/golem-architecture/blob/5fd05a316d40032f5a8180668d962f2dbd7c0d50/arch-snapshot/arch.md#L556)):*
> ```Markdown
>   forming a linear function. The counters [...]

2024-10-16 12:15 UTC, kamirr reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/110)* status: 0 of 1 files reviewed, 17 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 536 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O8Mz2gqEz3MZPLcRM7Z:-O8kvaJY5Q5ZKfrTKl3Y:bo6ir37) ([raw file](https://github.com/golemfactory/golem-architecture/blob/5fd05a316d40032f5a8180668d962f2dbd7c0d50/arch-snapshot/arch.md#L536)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Is a "Payment platform" really only an identifier? Or is it a piece of software identified only identified by that identifier?
</blockquote></details>

It is merely an identifier. The first of its components identifies the driver which is a piece of software, but I think that much has been made clear.
___
*[`arch-snapshot/arch.md` line 537 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O8MOEt634iXSdAtwkeQ:-O8kvq3OC6nUnXfsUekc:b3a7fsz) ([raw file](https://github.com/golemfactory/golem-architecture/blob/5fd05a316d40032f5a8180668d962f2dbd7c0d50/arch-snapshot/arch.md#L537)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Dumb question - why is that so? I'm guessing that the driver dictates the meaning of the `network` and `token` fields. If their meaning is implementation-defined, why do we bother to structure them into `token` and and `network` rather than have a generic, implementation defined `driver_config`? It seems to me that some assumptions about the driver have been made here. E.g. can we use PayU? If no - why? What are these assumptions?
</blockquote></details>

Network and token are the current names for these two, but they're opaque to yagna. The drivers are free to reuse those for arbitrary purposes and this wouldn't stop you from writing a PayU driver. I do think that those are bad names unless we actually want to only allow blockchain payments, but that's what it is today.
___
*[`arch-snapshot/arch.md` line 539 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O8MO51xCPUwVsSuh-lI:-O8kwWdb8FfgBw7mqvo-:b-886gsx) ([raw file](https://github.com/golemfactory/golem-architecture/blob/5fd05a316d40032f5a8180668d962f2dbd7c0d50/arch-snapshot/arch.md#L539)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

extra space?
</blockquote></details>

Fixed
___
*[`arch-snapshot/arch.md` line 543 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O8MWnx48dQxchWU2Mn2:-O8kxHLh6fMC_1Hst_Do:b-886gsx) ([raw file](https://github.com/golemfactory/golem-architecture/blob/5fd05a316d40032f5a8180668d962f2dbd7c0d50/arch-snapshot/arch.md#L543)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I don't understand why there is enumeration in this subsection. Especially the second point seems disconnected from the other two. Is this the right text structure optimal here?
</blockquote></details>

Fixed
___
*[`arch-snapshot/arch.md` line 545 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O8MRWAU0COTzR-5dudl:-O8kxd6V5qjXd9_J1kXR:b4l1xt1) ([raw file](https://github.com/golemfactory/golem-architecture/blob/5fd05a316d40032f5a8180668d962f2dbd7c0d50/arch-snapshot/arch.md#L545)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

It's unclear to me what you mean by "abstract computation". Would this be still true?
> - A payment model is an algorithm for determining the resource price based on resource usage (AKA Usage Counters)

BTW, is it the payment model, which governs whether there are mid-agreement payments? If yes, let's write explicitly about it because it is not clear neither from your or my description.

An example would be nice, so that the reader can build an intuition.
</blockquote></details>

Mid-agreement payments are not part of the payment model abstraction -- it only models pricing based on usage. Is the linear payment model not a sufficient examples?

I've reworded this because an `abstract computation` might in fact sound too abstract.
___
*[`arch-snapshot/arch.md` line 550 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O8MZdt6-qOhJGdRMpJ5:-O8kyePyEcY1qRJYMbyD:bxihxdt) ([raw file](https://github.com/golemfactory/golem-architecture/blob/5fd05a316d40032f5a8180668d962f2dbd7c0d50/arch-snapshot/arch.md#L550)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

This point seems a bit out of place. Or was your intention to describe how an implementation of this layer is instantiated? If that is the case than please make it explicit. E.g.
> A Payment Model is an inherent part of an Agreement. It is subject to negotiation between ...
</blockquote></details>

Reworded
___
*[`arch-snapshot/arch.md` line 555 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O8MaOJj9_p-xuNBwOCi:-O8l-Fj339LkyUuEP7U7:bi4uj3a) ([raw file](https://github.com/golemfactory/golem-architecture/blob/5fd05a316d40032f5a8180668d962f2dbd7c0d50/arch-snapshot/arch.md#L555)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

This needs to be expanded. Where do the constant coefficients and the constant come from? If I'm not mistaken, the usage counters are defined by the execution layer. If so, are payment models execution unit specific?

BTW, are there no counters for GPU time or memory (be it main memory or GPU memory)?
</blockquote></details>

I've expanded this section. Regarding GPU counters -- I believe there aren't any.
___
*[`arch-snapshot/arch.md` line 556 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O8Mi256EdsiKbl52_nq:-O8l-MVj32bd_FpcFzmy:b-7jzv7t) ([raw file](https://github.com/golemfactory/golem-architecture/blob/5fd05a316d40032f5a8180668d962f2dbd7c0d50/arch-snapshot/arch.md#L556)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

"during the lifetime of the Agreement", right?
</blockquote></details>

right
___
*[`arch-snapshot/arch.md` line 556 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O8N9kpF1SIx8nLrL2A4:-O9K1XQE8w6h8lZW4Frw:bxihxdt) ([raw file](https://github.com/golemfactory/golem-architecture/blob/5fd05a316d40032f5a8180668d962f2dbd7c0d50/arch-snapshot/arch.md#L556)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

In general, this section looks like a collection of facts, with no guiding thought. We should change it. Please find a way to organize these facts - be it by control flow or by aspects.
</blockquote></details>

Reworded
___
*[`arch-snapshot/arch.md` line 557 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O8MuLDL5CZ33T6CwPmk:-O8l-UwiEF9cSz8CDFbD:b-kkjn5i) ([raw file](https://github.com/golemfactory/golem-architecture/blob/5fd05a316d40032f5a8180668d962f2dbd7c0d50/arch-snapshot/arch.md#L557)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Are they a separate step, really? I thought they are treated just like any other property
</blockquote></details>

They are cruciall semantically, you could ignore other properties but you wouldn't ignore payments. Do you think there's a better term for that?
___
*[`arch-snapshot/arch.md` line 577 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O8MxlAb9FTGvfK_9w4b:-O9K1Yo60ZsTMXsZMq9V:bb6un1j) ([raw file](https://github.com/golemfactory/golem-architecture/blob/5fd05a316d40032f5a8180668d962f2dbd7c0d50/arch-snapshot/arch.md#L577)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

What is a driver? This is the firs occurrence of this work in the document.
</blockquote></details>

Done
___
*[`arch-snapshot/arch.md` line 578 [...]

2024-10-18 13:19 UTC, dopiera requested changes
I think it looks much better now, thank you. I do have some more comments, though.

PTAL at the rest of the document - we're attempting to:
* call entities in the system consistently (e.g. create a distinction between a Requestor (person) and a Requestor Agent (piece of software) - please take a look at the code already merged and try to mimic this
* cross reference the terms used (i.e. put links to relevant sections to make it easy for the reader to navigate) - please add such links to your text - also use the already merged documentation for reference
* capitalize the terms which have special meaning in Golem (e.g. Requestor) - please make sure you do, too

I think we should describe batching, too.

> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-:-O9TVmVx-nvhA6WdEBFa:b-97e4y9)* status: 0 of 1 files reviewed, 15 unresolved discussions (waiting on @kamirr)

___
*[`arch-snapshot/arch.md` line 557 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O8MuLDL5CZ33T6CwPmk:-O9TZpEp5tWO9MY6VJZZ:b-lhgg6m) ([raw file](https://github.com/golemfactory/golem-architecture/blob/5fd05a316d40032f5a8180668d962f2dbd7c0d50/arch-snapshot/arch.md#L557)):*
ACK. Maybe "element" then? Or "aspect"? Or rewrite the sentence altogether to something along these lines:
> Provider and Requestor must establish the mechanics of payments (Payment Driver, its parameters (e.g. specific blockchain), Payment Model) during the agreement Negotiation.
___
*[`arch-snapshot/arch.md` line 611 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O8NBa7z-W-EyA_VdMMK:-O9UXNOc2c4Zoq8CGsqE:beohkqe) ([raw file](https://github.com/golemfactory/golem-architecture/blob/5fd05a316d40032f5a8180668d962f2dbd7c0d50/arch-snapshot/arch.md#L611)):*
<details><summary><i>Previously, kamirr (Kamil Koczurek) wrote…</i></summary><blockquote>

Confirmation is confirmation -- checking whether a payment has actually been made successfully. It's the same as with normal banking -- you may be asked about a Transfer Confirmation, which would be a pdf document produced by the bank.

In case of blockchain it's a bit more convoluted because you only get a transaction ID from the requestor, and the provider must consult the blockchain itself (being the central authority) to see whether the transaction with the given ID actually exists and it's parameters match what the Requestor declared and the Provider expected.

Confirmations are also a fundamental term in Ethereum (and most other blockchains), which I suppose ties back to the assumption that we can produce a technical document regarding blockchain while assuming no knowledge of blockchain. See one of my previous comments for my thoughts on that.
</blockquote></details>

Why not include what you just wrote in the doc? I'm pretty sure you can come up with a two-sentence explanation of what how the confirmations relate to blockchain concepts and what purpose they serve.
___
*[`arch-snapshot/arch.md` line 544 at r2](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O9TV7AwBiVPEPXXB9c0:-O9TV7AwBiVPEPXXB9c1:b2ni52o) ([raw file](https://github.com/golemfactory/golem-architecture/blob/688298e5b142a814b1de87d34498f03b8debfb0b/arch-snapshot/arch.md#L544)):*
> ```Markdown
>   - token – Defined by the driver.
> 
>   The payment platform is opaque to Golem and are only relevant for payments.
> ```

is?



_Code quote:_
```Markdown
are
```
___
*[`arch-snapshot/arch.md` line 547 at r2](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O9TVW9a4Q1a86PnRQL2:-O9TVW9b0JWdrh_ZIHMz:b-q6wigl) ([raw file](https://github.com/golemfactory/golem-architecture/blob/688298e5b142a814b1de87d34498f03b8debfb0b/arch-snapshot/arch.md#L547)):*
> ```Markdown
>   It is serialized as `{dirver}-{network}-{token}`.
> #### Payments models
> A payment model is an algorithm for determining the amount due based on resource usage (AKA Usage Counters, see `ExeUnits` section).
> ```

Link please



_Code quote:_
```Markdown
ExeUnits
```
___
*[`arch-snapshot/arch.md` line 552 at r2](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O9TWjbU-NqqeQqtfyq1:-O9TWjbU-NqqeQqtfyq2:b-3kp7kg) ([raw file](https://github.com/golemfactory/golem-architecture/blob/688298e5b142a814b1de87d34498f03b8debfb0b/arch-snapshot/arch.md#L552)):*
> ```Markdown
> counters by constant coefficients and adds a constant on top of that, thus
> forming a linear function. The counters used today by yagna are cpu-time
> and total run-time.
> ```

Are you absolutely sure of that? Is this the case also for the GamerHash or the GPU provider? @nieznanysprawiciel - can you confirm this?



_Code quote:_
```Markdown
forming a linear function. The counters used today by yagna are cpu-time
and total run-time.
```
___
*[`arch-snapshot/arch.md` line 555 at r2](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O9TX9OA9VANZF7nFfQv:-O9TX9OA9VANZF7nFfQw:b2fab7x) ([raw file](https://github.com/golemfactory/golem-architecture/blob/688298e5b142a814b1de87d34498f03b8debfb0b/arch-snapshot/arch.md#L555)):*
> ```Markdown
> 
> The model parameters (for example coefficients of the linear Payment Model) are
> declared by the provider. Based on those, the requestor can make an informed
> ```

In an Offer, right? If that is the case, then please link make it explicit.



_Code quote:_
```Markdown
The model parameters (for example coefficients of the linear Payment Model) are
declared by the provider. Based on those, the requestor can make an informed
```
___
*[`arch-snapshot/arch.md` line 569 at r2](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O9TYuKqDdbF43DATaNq:-O9TYuKqDdbF43DATaNr:b-ml8q39) ([raw file](https://github.com/golemfactory/golem-architecture/blob/688298e5b142a814b1de87d34498f03b8debfb0b/arch-snapshot/arch.md#L569)):*
> ```Markdown
>     containing the model name, e.g. `linear`, as well as
>     `golem.com.pricing.model.{model_name}` which is an object containing
>     model-specific parameters.
> ```

That's interesting. According to #108 there are is no "object" type in the property language. It looks like we should chat over video to determine which is true.



_Code quote:_
```Markdown
    `golem.com.pricing.model.{model_name}` which is an object containing
    model-specific parameters.
```
___
*[`arch-snapshot/arch.md` line 654 at r2](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O9UZRzR8tXONBKkxum9:-O9UZRzR8tXONBKkxumA:b-7cpcha) ([raw file](https://github.com/golemfactory/golem-architecture/blob/688298e5b142a814b1de87d34498f03b8debfb0b/arch-snapshot/arch.md#L654)):*
> ```Markdown
>   - Accessing Ethereum is done via servers commonly called RPC endpoints.
>     A faulty endpoint could cause issues with transaction processing, so the
>     driver exposes them with some metadata to allow checking whether they work. 
> ```

It might be a dumb question, but I'll ask it anyway.

My understanding is that you're talking about Ethereum nodes' endpoints. What if there was a payment driver which didn't use the RPC API but had its own Ethereum node implementation linked in? Or didn't use Ethereum at all?



_Code quote:_
```Markdown
- Listing RPC endpoints*.
  - Accessing Ethereum is done via servers commonly called RPC endpoints.
    A faulty endpoint could cause issues with transaction processing, so the
    driver exposes them with some metadata to allow checking whether they work.
```
___
*[`arch-snapshot/arch.md` line 668 at r2](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O9U_kAg3iFJ_oagiBrp:-O9U_kAg3iFJ_oagiBrq:b-yqihno) ([raw file](https://github.com/golemfactory/golem-architecture/blob/688298e5b142a814b1de87d34498f03b8debfb0b/arch-snapshot/arch.md#L668)):*
> ```Markdown
> - Initialization.
>   - Drivers may need to perform some specific to them work before being able
>     to work. This method is the called before any transactions are scheduled.
> ```

This p [...]

2024-10-23 09:12 UTC, kamirr reviewed
If the user configures specific constraints on the demand, who's choosing the provider -- Requestor or Requestor Agent?

Re. batching, done.

> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-:-O9sccxZ3ZWuTSHKesGr:bsjydag)* status: 0 of 1 files reviewed, 15 unresolved discussions (waiting on @dopiera and @nieznanysprawiciel)

___
*[`arch-snapshot/arch.md` line 557 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O8MuLDL5CZ33T6CwPmk:-O9sY88Y08DKEzOYxcT1:bb6un1j) ([raw file](https://github.com/golemfactory/golem-architecture/blob/5fd05a316d40032f5a8180668d962f2dbd7c0d50/arch-snapshot/arch.md#L557)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

ACK. Maybe "element" then? Or "aspect"? Or rewrite the sentence altogether to something along these lines:
> Provider and Requestor must establish the mechanics of payments (Payment Driver, its parameters (e.g. specific blockchain), Payment Model) during the agreement Negotiation.
</blockquote></details>

Done
___
*[`arch-snapshot/arch.md` line 611 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O8NBa7z-W-EyA_VdMMK:-O9sZqd29bFL26A4pf2L:bb6un1j) ([raw file](https://github.com/golemfactory/golem-architecture/blob/5fd05a316d40032f5a8180668d962f2dbd7c0d50/arch-snapshot/arch.md#L611)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Why not include what you just wrote in the doc? I'm pretty sure you can come up with a two-sentence explanation of what how the confirmations relate to blockchain concepts and what purpose they serve.
</blockquote></details>

Done
___
*[`arch-snapshot/arch.md` line 544 at r2](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O9TV7AwBiVPEPXXB9c0:-O9sW2DO8PW4uOnHAcNb:bb6un1j) ([raw file](https://github.com/golemfactory/golem-architecture/blob/688298e5b142a814b1de87d34498f03b8debfb0b/arch-snapshot/arch.md#L544)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

is?
</blockquote></details>

Done
___
*[`arch-snapshot/arch.md` line 547 at r2](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O9TVW9a4Q1a86PnRQL2:-O9sWOvf3NVoxPZwSgup:bb6un1j) ([raw file](https://github.com/golemfactory/golem-architecture/blob/688298e5b142a814b1de87d34498f03b8debfb0b/arch-snapshot/arch.md#L547)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Link please
</blockquote></details>

Done
___
*[`arch-snapshot/arch.md` line 552 at r2](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O9TWjbU-NqqeQqtfyq1:-O9sWTRx5D7cg7kw4HIR:b-kg0umd) ([raw file](https://github.com/golemfactory/golem-architecture/blob/688298e5b142a814b1de87d34498f03b8debfb0b/arch-snapshot/arch.md#L552)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Are you absolutely sure of that? Is this the case also for the GamerHash or the GPU provider? @nieznanysprawiciel - can you confirm this?
</blockquote></details>

I am. This just means that GPU Providers can't offer usage-based pricing, but they can obviously raise the price to match the hardware offered. Note that unlike CPU, you cannot spin up multiple providers utilising one GPU (it's passed through to the VM directly and exclusively), meaning the GPU is wholly rented to the given requestor. This makes usage-based pricing less useful and I guess that's why it's not implemented.
___
*[`arch-snapshot/arch.md` line 555 at r2](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O9TX9OA9VANZF7nFfQv:-O9sXLb03yvuOvxIg7Xk:b-fa9sz8) ([raw file](https://github.com/golemfactory/golem-architecture/blob/688298e5b142a814b1de87d34498f03b8debfb0b/arch-snapshot/arch.md#L555)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

In an Offer, right? If that is the case, then please link make it explicit.
</blockquote></details>

clarified
___
*[`arch-snapshot/arch.md` line 569 at r2](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O9TYuKqDdbF43DATaNq:-O9sXQst-834D3dFc4tl:b-ta3f8w) ([raw file](https://github.com/golemfactory/golem-architecture/blob/688298e5b142a814b1de87d34498f03b8debfb0b/arch-snapshot/arch.md#L569)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

That's interesting. According to #108 there are is no "object" type in the property language. It looks like we should chat over video to determine which is true.
</blockquote></details>

Object as in givent `golem.com.pricing.model.linear` there exist properties of the form `golem.com.pricing.model.linear.PROP-NAME`. I don't think there's a better name for such a construct than `object`, but I can elaborate, although I believe this should be defined somewhere in the market offer specification language section.
___
*[`arch-snapshot/arch.md` line 654 at r2](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O9UZRzR8tXONBKkxum9:-O9sZvRD4aOAG8B49hdy:b-e9sf5p) ([raw file](https://github.com/golemfactory/golem-architecture/blob/688298e5b142a814b1de87d34498f03b8debfb0b/arch-snapshot/arch.md#L654)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

It might be a dumb question, but I'll ask it anyway.

My understanding is that you're talking about Ethereum nodes' endpoints. What if there was a payment driver which didn't use the RPC API but had its own Ethereum node implementation linked in? Or didn't use Ethereum at all?
</blockquote></details>

This is the problem with the current design. Notice that this point is marked with a `*`, I comment on that fact right below the list.
___
*[`arch-snapshot/arch.md` line 668 at r2](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O9U_kAg3iFJ_oagiBrp:-O9s_HDu1b0oUKUX2DJn:b-s1n50x) ([raw file](https://github.com/golemfactory/golem-architecture/blob/688298e5b142a814b1de87d34498f03b8debfb0b/arch-snapshot/arch.md#L668)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

This point is grammatically weird - can you please let chatgpt do its magic?
</blockquote></details>

Done, although I'm not all that sure it's any better.
___
*[`arch-snapshot/arch.md` line 675 at r2](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O9UaEsT8wQhDNn6vgDo:-O9s_Pb2AQUs39Wlr-5P:b-886gsx) ([raw file](https://github.com/golemfactory/golem-architecture/blob/688298e5b142a814b1de87d34498f03b8debfb0b/arch-snapshot/arch.md#L675)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

There's a weird line break here.
</blockquote></details>

Fixed
___
*[`arch-snapshot/arch.md` line 677 at r2](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O9UaQvp3XFStSw4ZDxi:-O9samr99oawlF2FJSDo:bb6un1j) ([raw file](https://github.com/golemfactory/golem-architecture/blob/688298e5b142a814b1de87d34498f03b8debfb0b/arch-snapshot/arch.md#L677)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

What are allocations? Please add a description in the "Important terms" section.
</blockquote></details>

Done
___
*[`arch-snapshot/arch.md` line 682 at r2](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O9UafPPBRMcf8-Hn6xg:-O9saoxkEry_41wxbn6U:beu06b9) ([raw file](https://github.com/golemfactory/golem-architecture/blob/688298e5b142a814b1de87d34498f03b8debfb0b/arch-snapshot/arch.md#L682)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I still don't get it. Why do we need a heuristic rather than just a simple check?
</blockquote></details>

This is due to the nature of ethereum -- it can temporarily split into inconsistent forks. The more blocks are confirmed since the transaction landed in the blokchain, the more confident can you  [...]

2024-10-23 23:19 UTC, dopiera reviewed
I get your point - for this case pick the one which your gut tells you is more frequent :)

> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-:-O9vehPP8egzda1MicD-:b5vxxj6)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @kamirr)

___
*[`arch-snapshot/arch.md` line 703 at r2](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O9UjEAD9_bZ9SlPPhLo:-O9uOK0r3nMHZnsqUcEp:b-p3m68o) ([raw file](https://github.com/golemfactory/golem-architecture/blob/688298e5b142a814b1de87d34498f03b8debfb0b/arch-snapshot/arch.md#L703)):*
<details><summary><i>Previously, kamirr (Kamil Koczurek) wrote…</i></summary><blockquote>

Done
</blockquote></details>

nit: s/build/built/


<!-- Sent from Reviewable.io -->

2024-10-31 10:06 UTC, kamirr reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/110)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 534 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O8MLDIo09RNa1EMOD_j:-OAX1_ivBpDYFslNDdM1:b-3mkmzd) ([raw file](https://github.com/golemfactory/golem-architecture/blob/5fd05a316d40032f5a8180668d962f2dbd7c0d50/arch-snapshot/arch.md#L534)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Since we're describing a payments component here, let's start with its interface. Let's not dive into code or the nitty-gritty, obscure details but the general idea. In particular I would like to learn:
* Which other components the does payments component interacts with?
* What is the relationship of this component to other components? (e.g. is there one per Agreement?)
* What is the lifecycle of this component?
* How do the other components invoke those payments (I presume there are multiple hooks in the process of performing Activities but honestly, I have no clue, so please describe them)? E.g.
  * when in the process?
  * what purpose do those serve?
  * what do they do?

If this component is further subdivided (e.g. some fixed part and swappable payment drivers), please include a decomposition of this component.
</blockquote></details>

Please check if the new revision answers your questions
___
*[`arch-snapshot/arch.md` line 703 at r2](https://reviewable.io/reviews/golemfactory/golem-architecture/110#-O9UjEAD9_bZ9SlPPhLo:-OAX-Z-X5bJLyw6T4MU8:bb6un1j) ([raw file](https://github.com/golemfactory/golem-architecture/blob/688298e5b142a814b1de87d34498f03b8debfb0b/arch-snapshot/arch.md#L703)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

nit: s/build/built/
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-10-31 15:38 UTC, dopiera approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/110)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kamirr)



<!-- Sent from Reviewable.io -->

2024-10-31 16:20 UTC, merged