Offers propagation
golemfactory/golem-architecture pull request #111
Opened 2024-10-09 17:24 UTC by nieznanysprawiciel

2024-10-17 20:51 UTC, dopiera requested changes
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/111)* status: 0 of 1 files reviewed, 17 unresolved discussions (waiting on @nieznanysprawiciel)

___
*[`arch-snapshot/arch.md` line 548 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9R3vLSBGaivsjOR05b:-O9R3vLSBGaivsjOR05c:b-3wywpm) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L548)):*
> ```Markdown
> propagated across the network, while Demands are not. This decision addresses an issue encountered in earlier versions of
> Golem, where Requestors joining the network were flooded with work Offers from all Nodes. By focusing on propagating
> Offers, the system prevents overload and ensures smoother interactions. Additionally, this approach enables Offers to be
> ```

I'd argue that it only kicks the can down road. Once there are enough Requestors looking for a Provider the same will happen to a provider who is joining the network, no?



_Code quote:_
```Markdown
prevents overload
```
___
*[`arch-snapshot/arch.md` line 549 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9R4W438mYXDs7QDUWV:-O9R4W438mYXDs7QDUWW:b-ox5y3k) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L549)):*
> ```Markdown
> Golem, where Requestors joining the network were flooded with work Offers from all Nodes. By focusing on propagating
> Offers, the system prevents overload and ensures smoother interactions. Additionally, this approach enables Offers to be
> available for other operations, such as [market searching](#searching-on-market).
> ```

I don't get it. Had we propagated Demands, too, we'd still be able to achieve it. Moreover, we'd be able to achieve more - we'd not only be able to scan the supply side, but also the demand side.



_Code quote:_
```Markdown
Offers, the system prevents overload and ensures smoother interactions. Additionally, this approach enables Offers to be
available for other operations, such as [market searching](#searching-on-market).
```
___
*[`arch-snapshot/arch.md` line 564 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9R5GGmDq3Fof-VtvzM:-O9R5GGmDq3Fof-VtvzN:b-kgxoyl) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L564)):*
> ```Markdown
> traffic optimization and is not crucial for the protocol.
> 
> The market broadcasting protocol is built on top of the Network Layer and makes only a few assumptions about it:
> ```

What about node discovery?



_Code quote:_
```Markdown
The market broadcasting protocol is built on top of the Network Layer and makes only a few assumptions about it:
```
___
*[`arch-snapshot/arch.md` line 565 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9R58HH8pLiC5sf-LCN:-O9R58HH8pLiC5sf-LCO:b354jbh) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L565)):*
> ```Markdown
> 
> The market broadcasting protocol is built on top of the Network Layer and makes only a few assumptions about it:
> - The Network Layer has broadcasting functionality that propagates messages to a specific neighborhood (the market
> ```

what's that?



_Code quote:_
```Markdown
specific neighborhood 
```
___
*[`arch-snapshot/arch.md` line 571 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9R5apB4CcuH1hxqjhd:-O9R5apB4CcuH1hxqjhe:b-xzns3j) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L571)):*
> ```Markdown
> #### Algorithm overview
> 
> There are three primary triggers for Offer propagation in the network:
> ```

Are these global events or local (uncoordinated, per-node)?



_Code quote:_
```Markdown
There are three primary triggers for Offer propagation in the network:
```
___
*[`arch-snapshot/arch.md` line 571 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9RAvMr18hjyC62phrM:-O9RAvMsDPBM9VFdU7Xa:b-pylh7p) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L571)):*
> ```Markdown
> #### Algorithm overview
> 
> There are three primary triggers for Offer propagation in the network:
> ```

I would love to learn what "propagate" means. Does every node possess full knowledge of all Offers on the market? Does "propagate" mean to send all known IDs? Or is there some diffing involved?



_Code quote:_
```Markdown
propagation
```
___
*[`arch-snapshot/arch.md` line 580 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9R5pBZ63uXgclx1Bg0:-O9R5pBZ63uXgclx1Bg1:b-d5xy94) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L580)):*
> ```Markdown
> 
> To minimize unnecessary data transfers, the propagation algorithm operates in two phases:
> - In the first phase, only the Offer IDs are broadcast to neighboring Nodes.
> ```

What are those? Is there some non-uniform topology of the network? If so, we should describe it in #112 - I didn't notice it there.

EDIT:
From what I read later in the document, a "neighbor" seems a marketplace concept (counter-intuitively). This begs an explanation on why this concept is needed. Also, am I right that two nodes servers in the same rack might not be neighbors, but a nodes in Europe and Australia may?

It seems we need a section on the topology and why this rather than any alternative. If what you've designed is a typical decentralized system, a link to a paper would be nice.



_Code quote:_
```Markdown
neighboring
```
___
*[`arch-snapshot/arch.md` line 762 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9RCHYK5nFGQssjeYFQ:-O9RCHYK5nFGQssjeYFR:bgcmohv) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L762)):*
> ```Markdown
> Optimal guarantees can be achieved when two neighboring Nodes have distinctly different neighborhoods, minimizing their
> number of common neighbors. Currently, in the Hybrid Net, neighborhood is determined based on the reversed Hamming
> distance between Node IDs.
> ```

I'm sorry, but I genuinely do not understand any of this. In particular, I don't understand:
* what a neighbor is
* what a neighborhood is
* what a broadcast function is
* what a neighborhood function is
* how that function affect the likelihood of a network partition



_Code quote:_
```Markdown
To prevent clustering of Nodes and accidental splits in the network, where subsets of Nodes become unreachable, a proper
neighborhood function must be utilized. This function is defined by the network module, and the market relies on the
broadcast function, leaving it with no alternative in this regard.

Optimal guarantees can be achieved when two neighboring Nodes have distinctly different neighborhoods, minimizing their
number of common neighbors. Currently, in the Hybrid Net, neighborhood is determined based on the reversed Hamming
distance between Node IDs.
```
___
*[`arch-snapshot/arch.md` line 768 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9RBYeT21w4Cj9c-u40:-O9RBYeT21w4Cj9c-u41:blgybzw) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L768)):*
> ```Markdown
> The net module implementation is transparent for the market module, but certain details must be addressed for network
> traffic optimization. The primary difference between the central and hybrid networks from the market perspective is that
> the central net has only global broadcasting, whereas the hybrid net utilizes local broadcasting to n [...]

2024-10-18 13:53 UTC, nieznanysprawiciel reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/111)* status: 0 of 1 files reviewed, 17 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 548 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9R3vLSBGaivsjOR05b:-O9UdR-C9w5EkGfSiJxp:b2u9tsi) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L548)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I'd argue that it only kicks the can down road. Once there are enough Requestors looking for a Provider the same will happen to a provider who is joining the network, no?
</blockquote></details>

There will be rather always more Providers than Requestor, because single Requestor needs in most cases more then 1 Provider to do work. Characteristic of Providers and Requestors is different. Providers are rather available most of the time observing the network. Requestors come, compute something and disappear.

If we want more detailed description of the motivations behind this decision, it should rather happen in the linked chapter. I just wanted to mention it here briefly.
___
*[`arch-snapshot/arch.md` line 549 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9R4W438mYXDs7QDUWV:-O9UerWBEnRuP63k2l5n:b-v8gx84) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L549)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I don't get it. Had we propagated Demands, too, we'd still be able to achieve it. Moreover, we'd be able to achieve more - we'd not only be able to scan the supply side, but also the demand side.
</blockquote></details>

Hmm, maybe it's overstatement that it enables market searching, it only makes it easier, because Offers are already everywhere and you don't need to negotiate.
And you might be right that asymmetry between position of Providers and Requestors (Requestors are more picky, Providers can be more willing to negotiate with anyone) could let us achieve more if the broadcasting would be reversed.

I will remove this sentence.
___
*[`arch-snapshot/arch.md` line 564 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9R5GGmDq3Fof-VtvzM:-O9Ugkce0Fp9MB3otfcI:b-whaveg) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L564)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

What about node discovery?
</blockquote></details>

Not sure what you mean? If market broadcasting protocol assumes node discovery? Or if it should be described here?

Broadcasting doesn't assume discovery. The second point states the requirement, that network layer has to provide ability to send GSB message to other Node. Discovery is hidden underneath, but market doesn't care about details as long he can say "Send this GSB message to NodeID"
___
*[`arch-snapshot/arch.md` line 565 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9R58HH8pLiC5sf-LCN:-O9UjG9K0AegxzGJfDH0:b-y08jv2) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L565)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

what's that?
</blockquote></details>

Changed to subset of Nodes
___
*[`arch-snapshot/arch.md` line 571 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9R5apB4CcuH1hxqjhd:-O9UsF7Z0-uADp-ww5mj:bhuu6lo) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L571)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Are these global events or local (uncoordinated, per-node)?
</blockquote></details>

Clarified
___
*[`arch-snapshot/arch.md` line 580 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9R5pBZ63uXgclx1Bg0:-O9UswY59zd8G8V9AcMp:b-nl95xo) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L580)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

What are those? Is there some non-uniform topology of the network? If so, we should describe it in #112 - I didn't notice it there.

EDIT:
From what I read later in the document, a "neighbor" seems a marketplace concept (counter-intuitively). This begs an explanation on why this concept is needed. Also, am I right that two nodes servers in the same rack might not be neighbors, but a nodes in Europe and Australia may?

It seems we need a section on the topology and why this rather than any alternative. If what you've designed is a typical decentralized system, a link to a paper would be nice.
</blockquote></details>

Neighbor is hybrid net concept, not marketplace. It is not described in networking, because it depends on implementation. Central net for example has no notion of neighborhood it sends broadcasts to whole network.

Ok, so now I understand the problem, I will think how to solve it. It seems that I shouldn't mention neighbors here but only broadcasts.
___
*[`arch-snapshot/arch.md` line 762 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9RCHYK5nFGQssjeYFQ:-O9UYb6GAcSkaUV_6xzc:b-6x64yb) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L762)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I'm sorry, but I genuinely do not understand any of this. In particular, I don't understand:
* what a neighbor is
* what a neighborhood is
* what a broadcast function is
* what a neighborhood function is
* how that function affect the likelihood of a network partition
</blockquote></details>

I think you should move this comment to PR: https://github.com/golemfactory/golem-architecture/pull/113
I was going to remove this description from here in next PR and leave only links to hybrid net description, because it's to detailed for this chapter. Nevertheless hybrid net description doesn't answer those questions enough as well, so I need to do it there.
___
*[`arch-snapshot/arch.md` line 778 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9RDRp43pGgM2_zjtpK:-O9UZypr5OwBhnJMXcEy:bsnnsyz) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L778)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Given that we're already defining some topology, where cycles might occur, can we call this "recurrent" to avoid confusion?
</blockquote></details>

Good idea, changed
___
*[`arch-snapshot/arch.md` line 780 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9RDakXDsQRYPvsYG6A:-O9U_HGx-Dwu5BIYtG2f:bqc9oc8) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L780)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I'm guessing these implement the "cyclic propagation", right?
</blockquote></details>

I assume that changing "cyclic" -> to "recurrent" removes the confusion?
___
*[`arch-snapshot/arch.md` line 780 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9RDlot8wid8KzF6ySY:-O9U_ftV6FYgI1HqUl-c:b-896fix) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L780)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote> [...]

2024-10-18 17:13 UTC, dopiera requested changes
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/111)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @nieznanysprawiciel)

___
*[`arch-snapshot/arch.md` line 548 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9R3vLSBGaivsjOR05b:-O9V_pMV7rypws5lfHn8:b-8x132w) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L548)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

There will be rather always more Providers than Requestor, because single Requestor needs in most cases more then 1 Provider to do work. Characteristic of Providers and Requestors is different. Providers are rather available most of the time observing the network. Requestors come, compute something and disappear.

If we want more detailed description of the motivations behind this decision, it should rather happen in the linked chapter. I just wanted to mention it here briefly.
</blockquote></details>

ACK, let's ignore it
___
*[`arch-snapshot/arch.md` line 564 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9R5GGmDq3Fof-VtvzM:-O9VaAlXCjf9CEgf-wIO:b308yq2) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L564)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

Not sure what you mean? If market broadcasting protocol assumes node discovery? Or if it should be described here?

Broadcasting doesn't assume discovery. The second point states the requirement, that network layer has to provide ability to send GSB message to other Node. Discovery is hidden underneath, but market doesn't care about details as long he can say "Send this GSB message to NodeID"
</blockquote></details>

Doesn't the market need to know of all (or some of) the nodes? If not, then please ignore my comment.
___
*[`arch-snapshot/arch.md` line 565 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9R58HH8pLiC5sf-LCN:-O9VaPsV4ARfzfmCQOth:bik63ux) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L565)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

Changed to subset of Nodes
</blockquote></details>

OK, but how does the market select the nodes (even if it doesn't know who they are). Is the marketplace aware of "the neighborhood"?
___
*[`arch-snapshot/arch.md` line 762 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9RCHYK5nFGQssjeYFQ:-O9Vb3q458I83QIR6K-W:b89li9y) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L762)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

I think you should move this comment to PR: https://github.com/golemfactory/golem-architecture/pull/113
I was going to remove this description from here in next PR and leave only links to hybrid net description, because it's to detailed for this chapter. Nevertheless hybrid net description doesn't answer those questions enough as well, so I need to do it there.
</blockquote></details>

At your service: https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VbKlg1HcduyffPnsz


<!-- Sent from Reviewable.io -->

2024-10-30 16:41 UTC, nieznanysprawiciel reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/111)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 564 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9R5GGmDq3Fof-VtvzM:-O9iXto61cWuZPoVW3Wu:bo0mndx) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L564)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Doesn't the market need to know of all (or some of) the nodes? If not, then please ignore my comment.
</blockquote></details>

For broadcasts it just uses operation provided by net, so there is no need to know any nodes. After receiving broadcast he needs to know who was sender of this broadcast and be able to send message to this Node. But discovery in this case is in net's responsibility.
___
*[`arch-snapshot/arch.md` line 565 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9R58HH8pLiC5sf-LCN:-O9iXbE208wijZqcWtC9:b-f0dt0f) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L565)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

OK, but how does the market select the nodes (even if it doesn't know who they are). Is the marketplace aware of "the neighborhood"?
</blockquote></details>

Market uses broadcast operation provided by net. It doesn't select Nodes itself.


<!-- Sent from Reviewable.io -->

2024-10-31 06:19 UTC, dopiera requested changes
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/111)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @nieznanysprawiciel)

___
*[`arch-snapshot/arch.md` line 580 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9R5pBZ63uXgclx1Bg0:-OAWDRNb78fInMYIU5ju:b-fprtht) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L580)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

Neighbor is hybrid net concept, not marketplace. It is not described in networking, because it depends on implementation. Central net for example has no notion of neighborhood it sends broadcasts to whole network.

Ok, so now I understand the problem, I will think how to solve it. It seems that I shouldn't mention neighbors here but only broadcasts.
</blockquote></details>

Shall we just say that it relies on the "broadcast" of the Net, which hides away all of its complexity?


<!-- Sent from Reviewable.io -->

2024-10-31 14:10 UTC, nieznanysprawiciel reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/111)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 571 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9RAvMr18hjyC62phrM:-OATTStnBA6wPeF7TR-N:b-jfls4s) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L571)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I would love to learn what "propagate" means. Does every node possess full knowledge of all Offers on the market? Does "propagate" mean to send all known IDs? Or is there some diffing involved?
</blockquote></details>

Changed to 
___
*[`arch-snapshot/arch.md` line 580 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9R5pBZ63uXgclx1Bg0:-OAXOduD2cUDu-x5CnQN:b-896fix) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L580)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Shall we just say that it relies on the "broadcast" of the Net, which hides away all of its complexity?
</blockquote></details>

Done.
___
*[`arch-snapshot/arch.md` line 768 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9RBYeT21w4Cj9c-u40:-OAXeu9t8hZm8HVEY9Ad:b-896fix) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L768)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I don't understand what this means.
</blockquote></details>

Done.
___
*[`arch-snapshot/arch.md` line 777 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9RD4t5-z27XSml-hDl:-OATSUv-9ZjI_ygtuaBm:bb7ivoc) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L777)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Which one is the primary?
</blockquote></details>

Changed to first
___
*[`arch-snapshot/arch.md` line 782 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9RDuFq3Oub6V_6qfU5:-OAXuP0l0BmSm-elaiIo:b-qx3egu) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L782)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

It's the first mention of storing anything. What are "stored Offers"?

BTW, why not all?
</blockquote></details>

added paragaph about storing
___
*[`arch-snapshot/arch.md` line 796 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9RE_Md8o2tfUnIgI-U:-OAXuR-4300SzbLoBwja:b-dg7pux) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L796)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

As mentioned before, I think we need to mention it earlier along with what is stored, what durability guarantees are there (is it only a cache?), etc.
</blockquote></details>

addded paragraph about storing Offers


<!-- Sent from Reviewable.io -->

2024-10-31 15:27 UTC, nieznanysprawiciel reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/111)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 792 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/111#-O9RESc56l8-cLgjxM0b:-OAYB6oWBTUN3WrDhRzQ:b-n9tkhd) ([raw file](https://github.com/golemfactory/golem-architecture/blob/94a991ff0ab7646e46ad965ad57e670cb8fc8ff3/arch-snapshot/arch.md#L792)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

What does it mean to invalidate a neighborhood?
</blockquote></details>

changed


<!-- Sent from Reviewable.io -->

2024-10-31 15:59 UTC, dopiera approved these changes
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/111)* status: 0 of 1 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-10-31 17:00 UTC, merged