Introduction to hybrid net
golemfactory/golem-architecture pull request #113
Opened 2024-10-16 17:33 UTC by nieznanysprawiciel

2024-10-18 17:02 UTC, dopiera requested changes
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/113)* status: 0 of 1 files reviewed, 20 unresolved discussions (waiting on @nieznanysprawiciel)

___
*[`arch-snapshot/arch.md` line 566 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VYovi1C9oHqooZm-g:-O9VYovi1C9oHqooZm-h:b-5wr0gc) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L566)):*
> ```Markdown
> 
> Hybrid Net was developed as an intermediate step towards decentralization, enabling peer-to-peer (P2P) communication 
> between Golem Nodes. However, since most of the network operates behind NATs, P2P cannot be the sole communication
> ```

between some of the Golem Nodes



_Code quote:_
```Markdown
between Golem Nodes
```
___
*[`arch-snapshot/arch.md` line 567 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9UmTpWBHwLdYSj_SXf:-O9UmTpWBHwLdYSj_SXg:bfrkcu4) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L567)):*
> ```Markdown
> Hybrid Net was developed as an intermediate step towards decentralization, enabling peer-to-peer (P2P) communication 
> between Golem Nodes. However, since most of the network operates behind NATs, P2P cannot be the sole communication
> method. To address this, the Net implementation supports communication forwarding through specialized Node known
> ```

Is this really a Node? As in Yagna Node?



_Code quote:_
```Markdown
Node
```
___
*[`arch-snapshot/arch.md` line 568 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9UmQEDEtBsHQ9x0nuZ:-O9UmQEDEtBsHQ9x0nu_:b-ci0xlz) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L568)):*
> ```Markdown
> between Golem Nodes. However, since most of the network operates behind NATs, P2P cannot be the sole communication
> method. To address this, the Net implementation supports communication forwarding through specialized Node known
> as relay.  
> ```

stray whitespace



_Code quote:_
```Markdown
··
```
___
*[`arch-snapshot/arch.md` line 579 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VMIp22KRxxEmEO44z:-O9VMIp22KRxxEmEO45-:buu4c0l) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L579)):*
> ```Markdown
> register with the Relay server, providing the necessary information for discovery and connection. The Relay server:
> - Maintains a list of Nodes present in the network.
> - Stores each Node's identity, public key, and IP address.
> ```

Could you elaborate more on the public key? Is it a part of the identity? Or is it ephemeral for network communication only?



_Code quote:_
```Markdown
public key
```
___
*[`arch-snapshot/arch.md` line 584 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VMw-H5POw_ECZ_Fh_:-O9VMw-I0Z02fVgg4njh:b-44sxa0) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L584)):*
> ```Markdown
> - Checks if connecting Nodes have public IP port exposed
> - Offers functions for:
>   - Discovering Nodes and querying their information.
> ```

What is there to discover? All nodes are connected to the relay, no?



_Code quote:_
```Markdown
Discovering 
```
___
*[`arch-snapshot/arch.md` line 589 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VU-ri5AmKWcpaqUQf:-O9VU-ri5AmKWcpaqUQg:b-wkv008) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L589)):*
> ```Markdown
> Communication with the Relay server is handled through a custom protocol built on top of UDP, defined using Protocol 
> Buffers (protobuf). UDP was chosen for its lightweight nature, as it does not require maintaining open connections, 
> which would consume more system resources compared to TCP. This makes it possible to handle a large number of Nodes 
> ```

I love dumb questions, so I can't resist this one: isn't this a premature optimization?

For every Node on the network you need to keep its identity, public keys, IP address and probably some overheads. Is this really that much smaller than the kernel memory footprint for a TCP connection? Besides, even if we assume that an idle TCP connection eats up 1K of kernel memory, you can have 1e6 machines connected per every GB of memory. I'd dare to say that 1M machines is way more than a single relay can handle anyway.



_Code quote:_
```Markdown
Buffers (protobuf). UDP was chosen for its lightweight nature, as it does not require maintaining open connections,
which would consume more system resources compared to TCP. This makes it possible to handle a large number of Nodes
```
___
*[`arch-snapshot/arch.md` line 590 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VNJsg38EFkAHJ_4rH:-O9VNJsg38EFkAHJ_4rI:b5qe005) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L590)):*
> ```Markdown
> Buffers (protobuf). UDP was chosen for its lightweight nature, as it does not require maintaining open connections, 
> which would consume more system resources compared to TCP. This makes it possible to handle a large number of Nodes 
> concurrently, ensuring decent scalability.
> ```

Does this apply to relaying communication between nodes behind NATs as well? Is yes, then how?



_Code quote:_
```Markdown
Communication with the Relay server is handled through a custom protocol built on top of UDP, defined using Protocol
Buffers (protobuf). UDP was chosen for its lightweight nature, as it does not require maintaining open connections,
which would consume more system resources compared to TCP. This makes it possible to handle a large number of Nodes
concurrently, ensuring decent scalability.
```
___
*[`arch-snapshot/arch.md` line 608 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VRWxP2qx8cwbVnndo:-O9VRWxP2qx8cwbVnndp:b-qfsjd3) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L608)):*
> ```Markdown
> which must compute a hash with a specified number of leading zeros. The difficulty level, set by the Relay server, 
> determines the number of leading zeros required. This computationally expensive task protects the Relay server from 
> DDoS attacks by forcing the Node to complete a certain amount of work before establishing a Session.  
> ```

Stray whitespace



_Code quote:_
```Markdown
··
```
___
*[`arch-snapshot/arch.md` line 610 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VODCS3VleCEwUv7MD:-O9VODCS3VleCEwUv7ME:b1goq59) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L610)):*
> ```Markdown
> DDoS attacks by forcing the Node to complete a certain amount of work before establishing a Session.  
> 
> The challenge is cryptographically signed using the private key of each identity associated with the Node. The Relay 
> ```

response, right?



_Code quote:_
```Markdown
 challenge
```
___
*[`arch-snapshot/arch.md` line 611 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VOVlW8h4DfM3ixHOM:-O9VOVlW8h4DfM3ixHON:b69rbhf) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L611)):*
> ```Markdown
> 
> The challenge is cryptographically signed using the private key of each identity associated with the Node. The Relay 
> server can then recover the Node's identities and public keys from these signatures, verifying that the Node 
> ```

ext [...]

2024-10-18 17:12 UTC, dopiera requested changes
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/113)* status: 0 of 1 files reviewed, 21 unresolved discussions (waiting on @nieznanysprawiciel)

___
*[`arch-snapshot/arch.md` line 563 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VbKlg1HcduyffPnsz:-O9VbKlg1HcduyffPnt-:beipla7) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L563)):*
> ```Markdown
> specifically for transfers.
> 
> #### Hybrid Net
> ```

Moving a comment from #111 
I'm sorry, but I genuinely do not understand any of this. In particular, I don't understand:
* what a neighbor is
* what a neighborhood is
* what a broadcast function is
* what a neighborhood function is
* how that function affect the likelihood of a network partition



_Code quote:_
```Markdown
#### Hybrid Net
```


<!-- Sent from Reviewable.io -->

2024-10-21 11:19 UTC, nieznanysprawiciel reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/113)* status: 0 of 1 files reviewed, 21 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 567 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9UmTpWBHwLdYSj_SXf:-O9illGZ7wuyZYXvRtRp:b-hn5wry) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L567)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Is this really a Node? As in Yagna Node?
</blockquote></details>

I probably so much wanted relay to be real Node :(
___
*[`arch-snapshot/arch.md` line 568 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9UmQEDEtBsHQ9x0nuZ:-O9il_jF9tDUc4nR3l8w:b-896fix) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L568)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

stray whitespace
</blockquote></details>

Done.
___
*[`arch-snapshot/arch.md` line 584 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VMw-H5POw_ECZ_Fh_:-O9imMgH2kKOLhCjePRE:bkglt6n) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L584)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

What is there to discover? All nodes are connected to the relay, no?
</blockquote></details>

This is what I would call discovery :D finding out information about Node
Otherwise we don't have discovery at all
I changed to only mention query node information, to make it less controversial
___
*[`arch-snapshot/arch.md` line 608 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VRWxP2qx8cwbVnndo:-O9ilTG_Eps1dbVKebDK:b-896fix) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L608)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Stray whitespace
</blockquote></details>

Done.
___
*[`arch-snapshot/arch.md` line 610 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VODCS3VleCEwUv7MD:-O9ilNbsClXLpugXgMSh:b-896fix) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L610)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

response, right?
</blockquote></details>

Done.
___
*[`arch-snapshot/arch.md` line 611 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VOVlW8h4DfM3ixHOM:-O9ikknV0scAVRqFRXYB:b-gcueg5) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L611)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

extract?
</blockquote></details>

I checked that not only in our code but in general people use term recover in case of ECDSA.
___
*[`arch-snapshot/arch.md` line 612 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VOZag1EM11xuSItYl:-O9il3sC-wcjs2SeTSdq:bjgscid) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L612)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

extracted?
</blockquote></details>

People use term recover
___
*[`arch-snapshot/arch.md` line 619 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VOfL31Cy8Onb-LWqI:-O9ikTfi50KGKCxTljrg:b-896fix) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L619)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

ICMP packet
</blockquote></details>

Done.
___
*[`arch-snapshot/arch.md` line 672 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VRu6OE41XhKbRFD1c:-O9imzlf-trB95JEMJlO:b-896fix) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L672)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

trailing whitespace
</blockquote></details>

Done.
___
*[`arch-snapshot/arch.md` line 674 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VS3T1-1OiVOz06oPE:-O9in9dR2W1CVeMiv05w:b-896fix) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L674)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I think it's called either "hole punching", or "NAT traversal", or "NAT punch through" but not "NAT punching".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-21 11:22 UTC, nieznanysprawiciel reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/113)* status: 0 of 1 files reviewed, 21 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 622 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VP6uv4Wbzdrg8kvIB:-O9incuV1Nd1y73tM5wp:bx9w04c) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L622)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Is there a designated port for that? You could get unlucky and accidentally reach a port of a different Yagna behind the same NAT. Imagine a server room with 100 servers, where each server has a running Yagna. If all of them are behind the same NAT, the likelihood of this event happening is roughly 1-(1-100/65536)**100 which is 15%.
</blockquote></details>

It's relay server that has separate port. Yagna node has only one UDP port for listening to external connections


<!-- Sent from Reviewable.io -->

2024-10-21 11:25 UTC, nieznanysprawiciel reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/113)* status: 0 of 1 files reviewed, 21 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 636 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VQ_He3Gtt1aa6HdVB:-O9ioA_D7QtpS2ruVfF_:bc7iyo8) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L636)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I must be missing something. What prevents me from grabbing your NodeId and presenting myself to the relay with a public key for my own private key rather than yours?
</blockquote></details>

It's good point. It wasn't mentioned anywhere that NodeId is derived from public key, so you can't do that.
But I think it should be rather described in Identity chapter. I added to our task on board that it should be described


<!-- Sent from Reviewable.io -->

2024-10-21 11:38 UTC, nieznanysprawiciel reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/113)* status: 0 of 1 files reviewed, 21 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 589 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VU-ri5AmKWcpaqUQf:-O9iqDlG9Xze-nrQBO0x:b5ksk4) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L589)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I love dumb questions, so I can't resist this one: isn't this a premature optimization?

For every Node on the network you need to keep its identity, public keys, IP address and probably some overheads. Is this really that much smaller than the kernel memory footprint for a TCP connection? Besides, even if we assume that an idle TCP connection eats up 1K of kernel memory, you can have 1e6 machines connected per every GB of memory. I'd dare to say that 1M machines is way more than a single relay can handle anyway.
</blockquote></details>

![image.png](https://files.reviewableusercontent.io/images/reviewable/10420306/nbGpMxalKl4WIIC71zW4Lz1K/image.png)
It's more than that, because there are tcp buffers. The middle values is default on my ubuntu at least.
It's actually less than I expected. Out embedded stack has much bigger buffers for optimal transfers.

But there are other reasons as well. For example we need to forward traffic on UDP anyway. So we would need separate UDP and TCP ports exposed. This would require changes to p2p sessions as well.
Maybe it could be said more in this chapter..


<!-- Sent from Reviewable.io -->

2024-10-21 20:07 UTC, dopiera requested changes
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/113)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @nieznanysprawiciel)

___
*[`arch-snapshot/arch.md` line 568 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9UmQEDEtBsHQ9x0nuZ:-O9kfdLnEU0ruvEuBh2w:b-97lfas) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L568)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still see it
___
*[`arch-snapshot/arch.md` line 589 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VU-ri5AmKWcpaqUQf:-O9kfiKA0PArEKtHbHsm:b-ip86u2) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L589)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

![image.png](https://files.reviewableusercontent.io/images/reviewable/10420306/nbGpMxalKl4WIIC71zW4Lz1K/image.png)
It's more than that, because there are tcp buffers. The middle values is default on my ubuntu at least.
It's actually less than I expected. Out embedded stack has much bigger buffers for optimal transfers.

But there are other reasons as well. For example we need to forward traffic on UDP anyway. So we would need separate UDP and TCP ports exposed. This would require changes to p2p sessions as well.
Maybe it could be said more in this chapter..
</blockquote></details>

Makes sense - especially the fact that we need UDP anyway.
___
*[`arch-snapshot/arch.md` line 611 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VOVlW8h4DfM3ixHOM:-O9kfrGp9xozMPN9COO6:b2nha9w) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L611)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

I checked that not only in our code but in general people use term recover in case of ECDSA.
</blockquote></details>

ACK
___
*[`arch-snapshot/arch.md` line 612 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VOZag1EM11xuSItYl:-O9kft0t5HQZPaWvH72b:b2nha9w) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L612)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

People use term recover
</blockquote></details>

ACK


<!-- Sent from Reviewable.io -->

2024-10-22 09:30 UTC, dopiera requested changes
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/113)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @nieznanysprawiciel)

___
*[`arch-snapshot/arch.md` line 802 at r3](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9nW2Wj9Nh-qDMBQMXi:-O9nW2Wj9Nh-qDMBQMXj:b-lwc1wf) ([raw file](https://github.com/golemfactory/golem-architecture/blob/cf13fd2ce4c15287adda7b3c7b6ac8b9ff6dddbe/arch-snapshot/arch.md#L802)):*
> ```Markdown
> significant application is in [the Offer Propagation algorithm](#offer-propagation). While the implementation of 
> specific algorithms is handled by other modules, the network module provides the necessary operations as building 
> blocks for these processes.
> ```

This is great, thank you for adding it.

I've got a dumb follow-up question, though. Before I ask the question, please verify my assumptions, which are:
* we're propagating only offer IDs and the offer themselves are then fetched by every provider directly from all providers
* eventually, every offer is known to every Node on the network

If this is correct and given the fact that the network is already centralized, why bother with the neighborhoods? Couldn't we do this instead?
* every Node publishes all its Offer IDs to the relay (or even the whole Offers)
* the relay aggregates *all* offers
* the relay periodically updates all Nodes with all the Offer ids (or even whole Offers)

I presume there is a logical answer - I'd be grateful if you added it to the document.



_Code quote:_
```Markdown
**What is a Neighborhood?**

Before diving into broadcasting, it's essential to understand the concept of a neighborhood. In a network, a
neighborhood is a subset of Nodes that are considered closest to a given Node based on an abstract metric. Each Node
has its own neighborhood. This metric doesn't necessarily reflect the real-world proximity of Nodes. For instance,
two Nodes on opposite sides of the globe could be neighbors, while two Nodes within the same physical network may be
too distant in terms of this metric to be in the same neighborhood.

In peer-to-peer networks, the concept of Node distance is often used for efficient Node discovery. However, since
the current Golem network layer relies on the Relay server for Node discovery, neighborhoods don't serve that
purpose. Although it’s conceivable that a fallback, such as a Kademlia-like implementation, could be used in the
event of a Relay server downtime, for now, the primary purpose of the neighborhood concept is broadcasting.

Broadcasting is a mechanism used by various algorithms to propagate information throughout the network. Its most
significant application is in [the Offer Propagation algorithm](#offer-propagation). While the implementation of
specific algorithms is handled by other modules, the network module provides the necessary operations as building
blocks for these processes.
```


<!-- Sent from Reviewable.io -->

2024-10-23 11:01 UTC, nieznanysprawiciel reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/113)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 563 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VbKlg1HcduyffPnsz:-O9t0zcZ6cj4qeV0J9V2:b-hcd70s) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L563)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Moving a comment from #111 
I'm sorry, but I genuinely do not understand any of this. In particular, I don't understand:
* what a neighbor is
* what a neighborhood is
* what a broadcast function is
* what a neighborhood function is
* how that function affect the likelihood of a network partition
</blockquote></details>

Does new chapter explaining neighborhood resolves this comment? Or is there something left to explain?
___
*[`arch-snapshot/arch.md` line 566 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VYovi1C9oHqooZm-g:-O9t1JGT-SxBhJk28NPG:b-896fix) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L566)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

between some of the Golem Nodes
</blockquote></details>

Done.
___
*[`arch-snapshot/arch.md` line 568 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9UmQEDEtBsHQ9x0nuZ:-O9syBoi28ALfY3xG6t2:b-hfg6x3) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L568)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I still see it
</blockquote></details>

Hmm, done again
___
*[`arch-snapshot/arch.md` line 803 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VXyKr3zYDGFkZ1ehL:-O9t0mkKC8EtZLLkfVhV:ber8zx7) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L803)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

As mentioned in some other review - I need more context here. I do understand that neighborhood is a concept from some DHT designs. If so, please mention it and introduce the reader to the concept.
</blockquote></details>

Does new chapter explaining neighborhood resolves this comment?
___
*[`arch-snapshot/arch.md` line 802 at r3](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9nW2Wj9Nh-qDMBQMXi:-O9syiHlEx5BeksiqNay:b-sdflc7) ([raw file](https://github.com/golemfactory/golem-architecture/blob/cf13fd2ce4c15287adda7b3c7b6ac8b9ff6dddbe/arch-snapshot/arch.md#L802)):*
> we're propagating only offer IDs and the offer themselves are then fetched by every provider directly from all providers

Full Offers are fetched from broadcast senders, not original authors


<!-- Sent from Reviewable.io -->

2024-10-23 22:41 UTC, dopiera requested changes
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/113)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @nieznanysprawiciel)

___
*[`arch-snapshot/arch.md` line 563 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VbKlg1HcduyffPnsz:-O9vB0aoElSdu4M_wVLU:b-s97k0u) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L563)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

Does new chapter explaining neighborhood resolves this comment? Or is there something left to explain?
</blockquote></details>

It does, thank you.
___
*[`arch-snapshot/arch.md` line 802 at r3](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9nW2Wj9Nh-qDMBQMXi:-O9vVPje5b76x9fODL4-:b-v7pz42) ([raw file](https://github.com/golemfactory/golem-architecture/blob/cf13fd2ce4c15287adda7b3c7b6ac8b9ff6dddbe/arch-snapshot/arch.md#L802)):*
ACK.

Regarding the essence of this comment and following up on our F2F discussion, how about adding this somewhere:
> Although HybridNet remains centralized for node discovery and relaying communication between Nodes behind NATs, broadcasting has already been designed in a decentralized manner as a step toward full network decentralization.
___
*[`arch-snapshot/arch.md` line 784 at r4](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9vU5JI5107rD4kJtxB:-O9vU5JJA3WBx8SSMpKK:b6s12li) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a465ca3cc878d108e9fc24bbd3ba3c26a6246c7f/arch-snapshot/arch.md#L784)):*
Let's start this section by stating the problem which this part of the Network abstraction is supposed to solve. 

How about something along these lines:
> Every Requestor needs to have a complete view of the market. Each Requestor contacting every Provider on the network to learn of their Offers would be a drastic scalability limitation. Hence we need smarter ways of disseminating information. These ways are abstracted away by the Network module in the form of the "Broadcast" method. HybridNet's implementation is inspired by [XYZ algorithm](https://www.lipsum.com/), which introduces the concept of neghborhoods.



_Code quote:_
```Markdown
##### Broadcasting and neighborhood
```
___
*[`arch-snapshot/arch.md` line 799 at r4](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9vTMxh7h_jcY_okHsE:-O9vTMxi50SWcrx7AGRx:bsaq6bb) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a465ca3cc878d108e9fc24bbd3ba3c26a6246c7f/arch-snapshot/arch.md#L799)):*
> ```Markdown
> event of a Relay server downtime, for now, the primary purpose of the neighborhood concept is broadcasting.
> 
> Broadcasting is a mechanism used by various algorithms to propagate information throughout the network. Its most 
> ```

As per my comment below - I don't think that's true in the generally accepted sense. "Broadcasting" is not really a mechanism - it's a name for the act of sending something to everybody.



_Code quote:_
```Markdown
Broadcasting is a mechanism used by various algorithms to propagate information throughout the network.
```
___
*[`arch-snapshot/arch.md` line 804 at r4](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9vKNTG3XCw_LaS8XmP:-O9vKNTG3XCw_LaS8XmQ:b1l9em9) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a465ca3cc878d108e9fc24bbd3ba3c26a6246c7f/arch-snapshot/arch.md#L804)):*
> ```Markdown
> blocks for these processes.
> 
> **Broadcasting**
> ```

I think I'm finally starting to understand where my confusion stems from. I think these are (correct me if I'm wrong) a rather unorthodox use of the word "broadcast" and a leaky abstraction of the HybridNet. It is my understanding that what you mean by "broadcast" is a way to send a similar message to all neighbors.

I consider the naming unorthodox is because usually broadcast means sending something to *all* participants of a network, not a subset (that's multicast).

I think that HybridNet's abstraction is leaky because the Markeplace needs to know of the network topology (i.e. what you call broadcast requires specifying some subset of nodes if I understood you correctly).

BTW, the fact that "propagation" has two meanings depending on the context doesn't help either:
  * the algorithm which Nodes obey (i.e. talking to neighbors and aggregating offers) to eventually disperse information from every Node to every Node
  * sending Offers from one Node to another

Here is a suggestion on how we can give words meanings to make it easier for readers:
* broadcast - a process of sending a bit of information to all the nodes on the network; in a naive implementation, it may be every node speaking to every node or there might be a central aggregator; in a P2P implementation it the information might be routed through neighbors
* propagation - the process built on top of Net, which makes sure that every Node sees every Offer
* transmit - the the act of sending offers or IDs to particular Nodes
* transmit to neighbors - the the act of sending offers or IDs to neighboring Nodes



_Code quote:_
```Markdown
**Broadcasting**
```


<!-- Sent from Reviewable.io -->

2024-10-24 12:07 UTC, nieznanysprawiciel reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/113)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 590 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VNJsg38EFkAHJ_4rH:-O9uQiDh0OyXXoQ-Z6sW:b-m4v3z6) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L590)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Does this apply to relaying communication between nodes behind NATs as well? Is yes, then how?
</blockquote></details>

There is `Forwarding Network Traffic` chapter describing this. Is there something lacking you would like there mentioned?
___
*[`arch-snapshot/arch.md` line 667 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VRBm5CBQE5NQ4QI_3:-O9yNIr00Bh7NhYq_rHo:b-p329ek) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L667)):*
I define Session in chapter `Connecting to Relay server`. Later in chapter `Peer-to-peer Session handshake` differences between Session with Relay vs. p2p Session are described.

I changed the descriptions in all places to consequently use word `Session` instead of connection. In earlier chapters when Session was not defined yet, I replaced connection with more general word communication.

>What makes those Sessions different from what you'd typically call a "connection"?

I think we used this word rather interchangeably. Session has more information in comparison to TCP connection for example. We have collection of all identities belonging on Node and some other information.
I checked definitions, it might be another non-standard usage of the word, but I would prefer to keep it, since we already use it this way.
___
*[`arch-snapshot/arch.md` line 802 at r3](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9nW2Wj9Nh-qDMBQMXi:-O9y2uTu4DdLLWTu_JkV:b3wvzlg) ([raw file](https://github.com/golemfactory/golem-architecture/blob/cf13fd2ce4c15287adda7b3c7b6ac8b9ff6dddbe/arch-snapshot/arch.md#L802)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

ACK.

Regarding the essence of this comment and following up on our F2F discussion, how about adding this somewhere:
> Although HybridNet remains centralized for node discovery and relaying communication between Nodes behind NATs, broadcasting has already been designed in a decentralized manner as a step toward full network decentralization.
</blockquote></details>

Good idea. I'm adding this in the introduction to Hybrid Net chapter
___
*[`arch-snapshot/arch.md` line 784 at r4](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9vU5JI5107rD4kJtxB:-O9yI1sN6eKlqa-B0SSO:b2wregr) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a465ca3cc878d108e9fc24bbd3ba3c26a6246c7f/arch-snapshot/arch.md#L784)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Let's start this section by stating the problem which this part of the Network abstraction is supposed to solve. 

How about something along these lines:
> Every Requestor needs to have a complete view of the market. Each Requestor contacting every Provider on the network to learn of their Offers would be a drastic scalability limitation. Hence we need smarter ways of disseminating information. These ways are abstracted away by the Network module in the form of the "Broadcast" method. HybridNet's implementation is inspired by [XYZ algorithm](https://www.lipsum.com/), which introduces the concept of neghborhoods.
</blockquote></details>

But this mixes problems from different layers. I wouldn't like to make chapters about net market-centric. Do you have any proposal that would be more neutral?
___
*[`arch-snapshot/arch.md` line 799 at r4](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9vTMxh7h_jcY_okHsE:-O9xqqZw98UglHlUxPgG:b-vernz8) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a465ca3cc878d108e9fc24bbd3ba3c26a6246c7f/arch-snapshot/arch.md#L799)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

As per my comment below - I don't think that's true in the generally accepted sense. "Broadcasting" is not really a mechanism - it's a name for the act of sending something to everybody.
</blockquote></details>

Changed to broadcasting operation
___
*[`arch-snapshot/arch.md` line 804 at r4](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9vKNTG3XCw_LaS8XmP:-O9yPy6fC3pr-wD8LgiV:b-7xhrc1) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a465ca3cc878d108e9fc24bbd3ba3c26a6246c7f/arch-snapshot/arch.md#L804)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I think I'm finally starting to understand where my confusion stems from. I think these are (correct me if I'm wrong) a rather unorthodox use of the word "broadcast" and a leaky abstraction of the HybridNet. It is my understanding that what you mean by "broadcast" is a way to send a similar message to all neighbors.

I consider the naming unorthodox is because usually broadcast means sending something to *all* participants of a network, not a subset (that's multicast).

I think that HybridNet's abstraction is leaky because the Markeplace needs to know of the network topology (i.e. what you call broadcast requires specifying some subset of nodes if I understood you correctly).

BTW, the fact that "propagation" has two meanings depending on the context doesn't help either:
  * the algorithm which Nodes obey (i.e. talking to neighbors and aggregating offers) to eventually disperse information from every Node to every Node
  * sending Offers from one Node to another

Here is a suggestion on how we can give words meanings to make it easier for readers:
* broadcast - a process of sending a bit of information to all the nodes on the network; in a naive implementation, it may be every node speaking to every node or there might be a central aggregator; in a P2P implementation it the information might be routed through neighbors
* propagation - the process built on top of Net, which makes sure that every Node sees every Offer
* transmit - the the act of sending offers or IDs to particular Nodes
* transmit to neighbors - the the act of sending offers or IDs to neighboring Nodes
</blockquote></details>

I applied terminology fixes discussed on standup. Not a lot of them, but probably there will be more significant changes in other PRs for example about Offers propagation


<!-- Sent from Reviewable.io -->

2024-10-24 12:08 UTC, nieznanysprawiciel reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/113)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 579 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VMIp22KRxxEmEO44z:-O9yQGoq8zo8eff8XGtQ:b-c18lls) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L579)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Could you elaborate more on the public key? Is it a part of the identity? Or is it ephemeral for network communication only?
</blockquote></details>

I added chapter about Node identification to explain more.
And another chapter about encryption is on the way which is going to explain relationships between different keys


<!-- Sent from Reviewable.io -->

2024-10-24 14:34 UTC, nieznanysprawiciel reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/113)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 777 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VWvqJ9YvGFYrqR7xd:-O9yQVgvBwohUQWj05Ef:b2nign6) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L777)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Still over the same Session, right?
</blockquote></details>

yes
___
*[`arch-snapshot/arch.md` line 777 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VX3hS3tvda983T-zi:-O9ylyS3B3zsuAVXJjVI:b-ej6c3) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L777)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Could you please rephrase this sentence so that it is 100% clear that:
* every reliable channel gets a new connection
* every data transfer gets a new connection
* everything else is squeezed into one connection (realiable?)
</blockquote></details>

But it doesn't work like you said. We have only single channel of each type.
It would be nice to have it implemented with ability to create channel, but it was ad hoc implementation to solve a problem not a fully designed concept


<!-- Sent from Reviewable.io -->

2024-10-24 15:28 UTC, dopiera requested changes
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/113)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @nieznanysprawiciel)

___
*[`arch-snapshot/arch.md` line 777 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VX3hS3tvda983T-zi:-O9z48yg2fX465kGbDJC:b8fya31) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L777)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

But it doesn't work like you said. We have only single channel of each type.
It would be nice to have it implemented with ability to create channel, but it was ad hoc implementation to solve a problem not a fully designed concept
</blockquote></details>

I get it that channels in general are described in #112, I still have a limited understanding of their lifecycles. In particular:
1. is there exactly one channel per triplet (NodeId pair, type of channel)?
2. if I understand your description correctly, there is 1:1 relationship between channels and TCP connections, except for unreliable channels; is that right?
3. is there exactly a single Session underpinning all channels with the same NodeId pair?

While the answer to the first question belongs to #112, I believe that answers to questions 2. and 3. should be answered here. Especially that I got it wrong as you say.
___
*[`arch-snapshot/arch.md` line 784 at r4](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9vU5JI5107rD4kJtxB:-O9z6_pp5omwAN1G12s3:bl9cuqf) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a465ca3cc878d108e9fc24bbd3ba3c26a6246c7f/arch-snapshot/arch.md#L784)):*
My intention is as follows:
1. Provide rationale for why need a Broadcast operation in the first place - granted, this should end up in #112.
2. Emphasize that a naive approach would not work, hence we need something smarter, which is why we're introducing the concept of neighbors.

Given that 1. should end up in #112 perhaps we should leave only something along these lines:
> Broadcasting information via a naive way, i.e. every Node contacting all other Nodes would be a drastic scalability limitation. Hence we need smarter ways of disseminating information. HybridNet's implementation is inspired by XYZ algorithm, which introduces the concept of neighborhoods.
___
*[`arch-snapshot/arch.md` line 799 at r4](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9vTMxh7h_jcY_okHsE:-O9z-StH0yB_y9n7Zj3U:b-lx2b7z) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a465ca3cc878d108e9fc24bbd3ba3c26a6246c7f/arch-snapshot/arch.md#L799)):*
I think I do understand what you mean but only because we talked about it before. How about rephrasing it slightly:
> A technique used in various broadcasting algorithms (**please link at least one**) involves disseminating information through the network by having each node send broadcast messages only to its neighbors, relying on those neighbors to forward the information further. HybridNet uses it as well.
___
*[`arch-snapshot/arch.md` line 804 at r4](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9vKNTG3XCw_LaS8XmP:-O9z2sEz0oChx960DvY2:bck3q43) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a465ca3cc878d108e9fc24bbd3ba3c26a6246c7f/arch-snapshot/arch.md#L804)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

I applied terminology fixes discussed on standup. Not a lot of them, but probably there will be more significant changes in other PRs for example about Offers propagation
</blockquote></details>

I still see some places, but let me resolve this comment and create comments in relevant places.
___
*[`arch-snapshot/arch.md` line 818 at r7](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9z1plY-0aol4th9kZr:-O9z1plZ-oLgf4uvS2oC:b-ic7qvf) ([raw file](https://github.com/golemfactory/golem-architecture/blob/e8add8cf9a359a80122e79a52e0fa4f1c29ae0e8/arch-snapshot/arch.md#L818)):*
> ```Markdown
> Its most significant application is in [the Offer Propagation algorithm](#offer-propagation). While the implementation of 
> specific algorithms is handled by other modules, the network module provides the necessary operations as building 
> blocks for these processes.
> ```

Doesn't this apply to broadcasting in general rather than the technique, which HybridNet uses under the hood? IMO such a sentence should be in  #112 to explain to the reader what the broadcast operation is for.



_Code quote:_
```Markdown
Its most significant application is in [the Offer Propagation algorithm](#offer-propagation). While the implementation of
specific algorithms is handled by other modules, the network module provides the necessary operations as building
blocks for these processes.
```
___
*[`arch-snapshot/arch.md` line 822 at r7](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9z30RU4Yhqyq0Ey4WK:-O9z30RU4Yhqyq0Ey4WL:b-angxol) ([raw file](https://github.com/golemfactory/golem-architecture/blob/e8add8cf9a359a80122e79a52e0fa4f1c29ae0e8/arch-snapshot/arch.md#L822)):*
That's not consistent with how we intended to use the word "broadcast", right? How about:
> HybridNet implements the broadcast operation via sending broadcast messages to the nearest neighborhood...



_Code quote:_
```Markdown
local broadcast operation that sends message to the nearest neighborhood of the Node.
```
___
*[`arch-snapshot/arch.md` line 822 at r7](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9z3Pyy0JwpmubyS2vf:-O9z3Pyy0JwpmubyS2vg:b-b9ybrf) ([raw file](https://github.com/golemfactory/golem-architecture/blob/e8add8cf9a359a80122e79a52e0fa4f1c29ae0e8/arch-snapshot/arch.md#L822)):*
> ```Markdown
> **Broadcasting**
> 
> Hybrid Net implements local broadcast operation that sends message to the nearest neighborhood of the Node. To query 
> ```

nit: stray space



_Code quote:_
```Markdown
·
```
___
*[`arch-snapshot/arch.md` line 824 at r7](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9z3NQW-5LzX8Myu8Tc:-O9z3NQW-5LzX8Myu8Td:b-b9ybrf) ([raw file](https://github.com/golemfactory/golem-architecture/blob/e8add8cf9a359a80122e79a52e0fa4f1c29ae0e8/arch-snapshot/arch.md#L824)):*
> ```Markdown
> Hybrid Net implements local broadcast operation that sends message to the nearest neighborhood of the Node. To query 
> its neighbors, a Node can send a `Neighborhood` request to the Relay server. The Relay server then responds with a 
> list of Nodes that are closest to the querying Node, based on a predefined metric. 
> ```

nit: stray space



_Code quote:_
```Markdown
·
```
___
*[`arch-snapshot/arch.md` line 829 at r7](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9z3SXiCh5vXO5BLqZa:-O9z3SXiCh5vXO5BLqZb:b-jq02qj) ([raw file](https://github.com/golemfactory/golem-architecture/blob/e8add8cf9a359a80122e79a52e0fa4f1c29ae0e8/arch-snapshot/arch.md#L829)):*
> ```Markdown
> chapter on [communication](#establishing-connections-between-nodes). The neighborhood algorithm does not 
> differentiate between Nodes capable of establishing peer-to-peer Sessions and those that require relayed 
> communication. Unlike IP-level broadcasts, Hybrid Net uses reliable channels for message transmission. 
> ```

nit: trailing space - actually there are many more - can you please fix them all?



_Code quote:_
```Markdown
·
```


<!-- Sent from Reviewable.io -->

2024-10-30 12:50 UTC, nieznanysprawiciel reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/113)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 799 at r4](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9vTMxh7h_jcY_okHsE:-OASSjwG0HpvzntfQdbW:b-tmnq6q) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a465ca3cc878d108e9fc24bbd3ba3c26a6246c7f/arch-snapshot/arch.md#L799)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I think I do understand what you mean but only because we talked about it before. How about rephrasing it slightly:
> A technique used in various broadcasting algorithms (**please link at least one**) involves disseminating information through the network by having each node send broadcast messages only to its neighbors, relying on those neighbors to forward the information further. HybridNet uses it as well.
</blockquote></details>

I linked to libp2p. I had hard time finding good description. I'm afraid that this will rather complicate things...


<!-- Sent from Reviewable.io -->

2024-10-30 14:34 UTC, nieznanysprawiciel reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/113)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 777 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VX3hS3tvda983T-zi:-OASk1sd3jjCJd6imdxT:b-on7xf1) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L777)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I get it that channels in general are described in #112, I still have a limited understanding of their lifecycles. In particular:
1. is there exactly one channel per triplet (NodeId pair, type of channel)?
2. if I understand your description correctly, there is 1:1 relationship between channels and TCP connections, except for unreliable channels; is that right?
3. is there exactly a single Session underpinning all channels with the same NodeId pair?

While the answer to the first question belongs to #112, I believe that answers to questions 2. and 3. should be answered here. Especially that I got it wrong as you say.
</blockquote></details>

I clarified point 3.

Hmm there is another implementation detail that I missed when it comes to question 2. There are actually 2 tcp connections per transport type (channel). One is used to send messages, other is used to receive messages from other party.

This is implementation detail, done for simplicity. Otherwise there are problems with synchronization. If 2 Nodes try to establish tcp connection at the same time, we end up with 2 connections anyway. We could avoid this, by having rules, which connection should be closed and which one should remain. This would be more error prone than current version.
In general there is much to lose and not much to gain.

I'm wondering, should I describe it?
I wouldn't like to dive so deep into implementation.


<!-- Sent from Reviewable.io -->

2024-10-30 16:36 UTC, nieznanysprawiciel reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/113)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 784 at r4](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9vU5JI5107rD4kJtxB:-OATHFOoB4VvZrpPz_LX:b-896fix) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a465ca3cc878d108e9fc24bbd3ba3c26a6246c7f/arch-snapshot/arch.md#L784)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

My intention is as follows:
1. Provide rationale for why need a Broadcast operation in the first place - granted, this should end up in #112.
2. Emphasize that a naive approach would not work, hence we need something smarter, which is why we're introducing the concept of neighbors.

Given that 1. should end up in #112 perhaps we should leave only something along these lines:
> Broadcasting information via a naive way, i.e. every Node contacting all other Nodes would be a drastic scalability limitation. Hence we need smarter ways of disseminating information. HybridNet's implementation is inspired by XYZ algorithm, which introduces the concept of neighborhoods.
</blockquote></details>

Done.
___
*[`arch-snapshot/arch.md` line 822 at r7](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9z30RU4Yhqyq0Ey4WK:-OATH6EH0812FEjDrAlg:b-896fix) ([raw file](https://github.com/golemfactory/golem-architecture/blob/e8add8cf9a359a80122e79a52e0fa4f1c29ae0e8/arch-snapshot/arch.md#L822)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

That's not consistent with how we intended to use the word "broadcast", right? How about:
> HybridNet implements the broadcast operation via sending broadcast messages to the nearest neighborhood...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-30 16:38 UTC, nieznanysprawiciel reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/113)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 784 at r4](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9vU5JI5107rD4kJtxB:-OATH_Tr4aZFHSi4n2_b:bitw1i) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a465ca3cc878d108e9fc24bbd3ba3c26a6246c7f/arch-snapshot/arch.md#L784)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Point 1 should be applied to the [Network](https://reviewable.io/reviews/golemfactory/golem-architecture/112) PR


<!-- Sent from Reviewable.io -->

2024-10-30 16:39 UTC, nieznanysprawiciel reviewed
Ok, so all changes targeting this PR are finished. There 2 comments that should be applied in https://reviewable.io/reviews/golemfactory/golem-architecture/112
I would prefer to apply them after we will have unified version. So maybe let's merge those PR first and later I will create new one to add necessary things?

> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-:-OATHkklEC5eP3xkgVnQ:bpa8949)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @dopiera)



<!-- Sent from Reviewable.io -->

2024-10-31 07:42 UTC, dopiera requested changes
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/113)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nieznanysprawiciel)

___
*[`arch-snapshot/arch.md` line 777 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-O9VX3hS3tvda983T-zi:-OAWVyxNA4BbGHvUtjtl:b-8f8wp9) ([raw file](https://github.com/golemfactory/golem-architecture/blob/b6543cdd6d565251ae5d8866f093da5351269519/arch-snapshot/arch.md#L777)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

I clarified point 3.

Hmm there is another implementation detail that I missed when it comes to question 2. There are actually 2 tcp connections per transport type (channel). One is used to send messages, other is used to receive messages from other party.

This is implementation detail, done for simplicity. Otherwise there are problems with synchronization. If 2 Nodes try to establish tcp connection at the same time, we end up with 2 connections anyway. We could avoid this, by having rules, which connection should be closed and which one should remain. This would be more error prone than current version.
In general there is much to lose and not much to gain.

I'm wondering, should I describe it?
I wouldn't like to dive so deep into implementation.
</blockquote></details>

Let's ignore it.
___
*[`arch-snapshot/arch.md` line 794 at r10](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-OAWVXnY3gryyr_-c1jp:-OAWVXnY3gryyr_-c1jq:bsfeel6) ([raw file](https://github.com/golemfactory/golem-architecture/blob/1accf0f54352a662659a0f09dc6018bc883b3738/arch-snapshot/arch.md#L794)):*
> ```Markdown
> types are distinguished by using separate TCP connections. This separation ensures that independent sender buffers 
> are maintained, preventing messages in one channel from being blocked by messages in the other. Each transport type 
> has its own single TCP connection. This means that independent transfers still can interfere with each other.
> ```

Sorry - dumb question. Are they even possible? I.e. is there some multiplexing on top of this TCP connection?



_Code quote:_
```Markdown
This means that independent transfers still can interfere with each other.
```


<!-- Sent from Reviewable.io -->

2024-10-31 10:19 UTC, nieznanysprawiciel reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/113)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 794 at r10](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-OAWVXnY3gryyr_-c1jp:-OAX4LK52NZMVrK1oXfH:b5mgf4b) ([raw file](https://github.com/golemfactory/golem-architecture/blob/1accf0f54352a662659a0f09dc6018bc883b3738/arch-snapshot/arch.md#L794)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Sorry - dumb question. Are they even possible? I.e. is there some multiplexing on top of this TCP connection?
</blockquote></details>

Yes, look at my answer in networking PR.


<!-- Sent from Reviewable.io -->

2024-10-31 14:40 UTC, dopiera requested changes
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/113)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nieznanysprawiciel)

___
*[`arch-snapshot/arch.md` line 794 at r10](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-OAWVXnY3gryyr_-c1jp:-OAXzbSd-VN33ZW2XbHv:b-r2rfgh) ([raw file](https://github.com/golemfactory/golem-architecture/blob/1accf0f54352a662659a0f09dc6018bc883b3738/arch-snapshot/arch.md#L794)):*
Following our F2F discussion - I think the word "transfer" creates confusion here. How about we replace this sentence with this?
> If multiple components within the same process need to use the transfer channel, they will share a single TCP connection, competing for bandwidth. As there is no fair scheduling mechanism, one component can easily starve another by producing messages at a sufficiently high rate.


<!-- Sent from Reviewable.io -->

2024-10-31 16:58 UTC, nieznanysprawiciel reviewed
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/113)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 794 at r10](https://reviewable.io/reviews/golemfactory/golem-architecture/113#-OAWVXnY3gryyr_-c1jp:-OAYVpgp5DkHieIkpGGj:b-896fix) ([raw file](https://github.com/golemfactory/golem-architecture/blob/1accf0f54352a662659a0f09dc6018bc883b3738/arch-snapshot/arch.md#L794)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Following our F2F discussion - I think the word "transfer" creates confusion here. How about we replace this sentence with this?
> If multiple components within the same process need to use the transfer channel, they will share a single TCP connection, competing for bandwidth. As there is no fair scheduling mechanism, one component can easily starve another by producing messages at a sufficiently high rate.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-03 16:08 UTC, dopiera approved these changes
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/113)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nieznanysprawiciel)



<!-- Sent from Reviewable.io -->

2024-11-03 16:08 UTC, merged