Rename entrypoint to init; formatting
golemfactory/golem-architecture pull request #65
Opened 2022-12-13 11:40 UTC by lucekdudek

2022-12-14 06:13 UTC, shadeofblue commented on gaps/gap-16_golem_compose/gaom.schema.json
> +  "$id": "https://golem.network/gaom.schema.json",
uhh - why is such a large update needed?... please don't do this

2022-12-14 06:14 UTC, shadeofblue requested changes
I don't think such a minimal change justifies a reformat of the whole `json` file...

2022-12-14 06:16 UTC, shadeofblue commented
@lucekdudek I usually have no problem with having files aligned to a common format ... but in this case I believe it's taken one step too far... please update the documents just where an update is needed and refrain from bulk updates just for the sake of your particular editor setup, thank you :bowing_man:

2022-12-16 10:18 UTC, lucekdudek commented
> @lucekdudek I usually have no problem with having files aligned to a common format ... but in this case I believe it's taken one step too far... please update the documents just where an update is needed and refrain from bulk updates just for the sake of your particular editor setup, thank you bowing_man

Fixed

2022-12-19 10:15 UTC, shadeofblue approved these changes

2022-12-19 12:28 UTC, merged

2022-12-19 21:59 UTC, stranger80 commented
This PR is missing an update to gaom schema entity diagram.
Let me add this as well.